// Code generated by protoc-gen-go. DO NOT EDIT.
// source: istioinstaller_types.proto

package v1alpha1

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	v11 "k8s.io/api/autoscaling/v1"
	v1 "k8s.io/api/core/v1"
	v1beta1 "k8s.io/api/policy/v1beta1"
	v12 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
//const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ProxyConfig_InterceptionMode int32

const (
	ProxyConfig_REDIRECT ProxyConfig_InterceptionMode = 0
	ProxyConfig_TPROXY   ProxyConfig_InterceptionMode = 1
)

var ProxyConfig_InterceptionMode_name = map[int32]string{
	0: "REDIRECT",
	1: "TPROXY",
}

var ProxyConfig_InterceptionMode_value = map[string]int32{
	"REDIRECT": 0,
	"TPROXY":   1,
}

func (x ProxyConfig_InterceptionMode) String() string {
	return proto.EnumName(ProxyConfig_InterceptionMode_name, int32(x))
}

func (ProxyConfig_InterceptionMode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_d0a1188b3d395975, []int{5, 0}
}

// InstallerSpec defines the desired state of IstioInstaller.
type InstallerSpec struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	// install_package_path is the URL for the install package to install e.g.
	//   http://github.com/istio/istio/releases/install/1.1.2
	//   http://github.com/istio/istio/releases/install/lts
	//   file://tmp/istio-installer/nightly
	// Optional. Uses compiled in install package by default.
	InstallPackagePath string `protobuf:"bytes,1,opt,name=install_package_path,json=installPackagePath,proto3" json:"install_package_path,omitempty"`
	// controller_name binds the CR to the install controller
	// that should listen to it. Used when multiple versions of controllers
	// coexist in a cluster and to prevent old versions of controller from
	// consuming new version of config.
	ControllerName string `protobuf:"bytes,2,opt,name=controller_name,json=controllerName,proto3" json:"controller_name,omitempty"`
	// hub is the root for docker images e.g. docker.io/istio-release.
	Hub string `protobuf:"bytes,3,opt,name=hub,proto3" json:"hub,omitempty"`
	// tag is the version tag for docker images e.g. 1.0.6
	Tag string `protobuf:"bytes,4,opt,name=tag,proto3" json:"tag,omitempty"`
	// default_namespace is the default namespace for components if their
	// namespace is not explicitly set. Required.
	DefaultNamespace string `protobuf:"bytes,5,opt,name=default_namespace,json=defaultNamespace,proto3" json:"default_namespace,omitempty"`
	// remote_cluster_config configures the cluster as a remote cluster.
	RemoteClusterConfig *RemoteClusterConfig `protobuf:"bytes,10,opt,name=remote_cluster_config,json=remoteClusterConfig,proto3" json:"remote_cluster_config,omitempty"`
	// Selection and configuration of core Istio features.
	TrafficManagement *TrafficManagementConfig `protobuf:"bytes,20,opt,name=traffic_management,json=trafficManagement,proto3" json:"traffic_management,omitempty"`
	Policy            *PolicyConfig            `protobuf:"bytes,21,opt,name=policy,proto3" json:"policy,omitempty"`
	Telemetry         *TelemetryConfig         `protobuf:"bytes,22,opt,name=telemetry,proto3" json:"telemetry,omitempty"`
	Security          *SecurityConfig          `protobuf:"bytes,23,opt,name=security,proto3" json:"security,omitempty"`
	ConfigManagement  *ConfigManagementConfig  `protobuf:"bytes,24,opt,name=config_management,json=configManagement,proto3" json:"config_management,omitempty"`
	// Ingress/egress gateway installation and configuration.
	IngressGateway []*IngressGatewayConfig `protobuf:"bytes,30,rep,name=ingress_gateway,json=ingressGateway,proto3" json:"ingress_gateway,omitempty"`
	EgressGateway  []*EgressGatewayConfig  `protobuf:"bytes,31,rep,name=egress_gateway,json=egressGateway,proto3" json:"egress_gateway,omitempty"`
	// List of external operators that will be installed (but not managed by)
	// IstioInstaller e.g. prometheus, grafana, kiali.
	ExternalOperators    []*OperatorConfig `protobuf:"bytes,50,rep,name=external_operators,json=externalOperators,proto3" json:"external_operators,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *InstallerSpec) Reset()         { *m = InstallerSpec{} }
func (m *InstallerSpec) String() string { return proto.CompactTextString(m) }
func (*InstallerSpec) ProtoMessage()    {}
func (*InstallerSpec) Descriptor() ([]byte, []int) {
	return fileDescriptor_d0a1188b3d395975, []int{0}
}

func (m *InstallerSpec) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InstallerSpec.Unmarshal(m, b)
}
func (m *InstallerSpec) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InstallerSpec.Marshal(b, m, deterministic)
}
func (m *InstallerSpec) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InstallerSpec.Merge(m, src)
}
func (m *InstallerSpec) XXX_Size() int {
	return xxx_messageInfo_InstallerSpec.Size(m)
}
func (m *InstallerSpec) XXX_DiscardUnknown() {
	xxx_messageInfo_InstallerSpec.DiscardUnknown(m)
}

var xxx_messageInfo_InstallerSpec proto.InternalMessageInfo

func (m *InstallerSpec) GetInstallPackagePath() string {
	if m != nil {
		return m.InstallPackagePath
	}
	return ""
}

func (m *InstallerSpec) GetControllerName() string {
	if m != nil {
		return m.ControllerName
	}
	return ""
}

func (m *InstallerSpec) GetHub() string {
	if m != nil {
		return m.Hub
	}
	return ""
}

func (m *InstallerSpec) GetTag() string {
	if m != nil {
		return m.Tag
	}
	return ""
}

func (m *InstallerSpec) GetDefaultNamespace() string {
	if m != nil {
		return m.DefaultNamespace
	}
	return ""
}

func (m *InstallerSpec) GetRemoteClusterConfig() *RemoteClusterConfig {
	if m != nil {
		return m.RemoteClusterConfig
	}
	return nil
}

func (m *InstallerSpec) GetTrafficManagement() *TrafficManagementConfig {
	if m != nil {
		return m.TrafficManagement
	}
	return nil
}

func (m *InstallerSpec) GetPolicy() *PolicyConfig {
	if m != nil {
		return m.Policy
	}
	return nil
}

func (m *InstallerSpec) GetTelemetry() *TelemetryConfig {
	if m != nil {
		return m.Telemetry
	}
	return nil
}

func (m *InstallerSpec) GetSecurity() *SecurityConfig {
	if m != nil {
		return m.Security
	}
	return nil
}

func (m *InstallerSpec) GetConfigManagement() *ConfigManagementConfig {
	if m != nil {
		return m.ConfigManagement
	}
	return nil
}

func (m *InstallerSpec) GetIngressGateway() []*IngressGatewayConfig {
	if m != nil {
		return m.IngressGateway
	}
	return nil
}

func (m *InstallerSpec) GetEgressGateway() []*EgressGatewayConfig {
	if m != nil {
		return m.EgressGateway
	}
	return nil
}

func (m *InstallerSpec) GetExternalOperators() []*OperatorConfig {
	if m != nil {
		return m.ExternalOperators
	}
	return nil
}

// InstallerStatus defines the observed state of IstioInstaller.
// TODO: this needs more work. What do we want to observe?
type InstallerStatus struct {
	ProxyControl         string   `protobuf:"bytes,1,opt,name=proxy_control,json=proxyControl,proto3" json:"proxy_control,omitempty"`
	SidecarInjector      string   `protobuf:"bytes,2,opt,name=sidecar_injector,json=sidecarInjector,proto3" json:"sidecar_injector,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InstallerStatus) Reset()         { *m = InstallerStatus{} }
func (m *InstallerStatus) String() string { return proto.CompactTextString(m) }
func (*InstallerStatus) ProtoMessage()    {}
func (*InstallerStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_d0a1188b3d395975, []int{1}
}

func (m *InstallerStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InstallerStatus.Unmarshal(m, b)
}
func (m *InstallerStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InstallerStatus.Marshal(b, m, deterministic)
}
func (m *InstallerStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InstallerStatus.Merge(m, src)
}
func (m *InstallerStatus) XXX_Size() int {
	return xxx_messageInfo_InstallerStatus.Size(m)
}
func (m *InstallerStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_InstallerStatus.DiscardUnknown(m)
}

var xxx_messageInfo_InstallerStatus proto.InternalMessageInfo

func (m *InstallerStatus) GetProxyControl() string {
	if m != nil {
		return m.ProxyControl
	}
	return ""
}

func (m *InstallerStatus) GetSidecarInjector() string {
	if m != nil {
		return m.SidecarInjector
	}
	return ""
}

// RemoteClusterConfig defines configuration options for remote clusters.
type RemoteClusterConfig struct {
	// Enabled selects whether the cluster is configured as remote.
	Enabled bool `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	// Namespace that all components for this feature are installed into.
	Namespace string `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	// resource_override is a kustomize style overlay to kubernetes resources
	// in the manifests rendered from the chart templates using included
	// values.yaml with ValuesOverride above.
	ResourceOverride     []*Object `protobuf:"bytes,3,rep,name=resource_override,json=resourceOverride,proto3" json:"resource_override,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *RemoteClusterConfig) Reset()         { *m = RemoteClusterConfig{} }
func (m *RemoteClusterConfig) String() string { return proto.CompactTextString(m) }
func (*RemoteClusterConfig) ProtoMessage()    {}
func (*RemoteClusterConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_d0a1188b3d395975, []int{2}
}

func (m *RemoteClusterConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoteClusterConfig.Unmarshal(m, b)
}
func (m *RemoteClusterConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoteClusterConfig.Marshal(b, m, deterministic)
}
func (m *RemoteClusterConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoteClusterConfig.Merge(m, src)
}
func (m *RemoteClusterConfig) XXX_Size() int {
	return xxx_messageInfo_RemoteClusterConfig.Size(m)
}
func (m *RemoteClusterConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoteClusterConfig.DiscardUnknown(m)
}

var xxx_messageInfo_RemoteClusterConfig proto.InternalMessageInfo

func (m *RemoteClusterConfig) GetEnabled() bool {
	if m != nil {
		return m.Enabled
	}
	return false
}

func (m *RemoteClusterConfig) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

func (m *RemoteClusterConfig) GetResourceOverride() []*Object {
	if m != nil {
		return m.ResourceOverride
	}
	return nil
}

// TrafficManagementConfig defines configuration options for proxy control and injection.
type TrafficManagementConfig struct {
	// Selects whether traffic management is installed.
	Enabled bool `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	// Namespace that all components for this feature are installed into.
	Namespace string `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	// When set to true, auto injection is controlled by namespace label and pod annotation.
	// When set to false, auto injection is completely disabled.
	AutoInjection bool `protobuf:"varint,3,opt,name=auto_injection,json=autoInjection,proto3" json:"auto_injection,omitempty"`
	// Component specific config.
	PilotConfig          *PilotConfig `protobuf:"bytes,4,opt,name=pilot_config,json=pilotConfig,proto3" json:"pilot_config,omitempty"`
	ProxyConfig          *ProxyConfig `protobuf:"bytes,5,opt,name=proxy_config,json=proxyConfig,proto3" json:"proxy_config,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *TrafficManagementConfig) Reset()         { *m = TrafficManagementConfig{} }
func (m *TrafficManagementConfig) String() string { return proto.CompactTextString(m) }
func (*TrafficManagementConfig) ProtoMessage()    {}
func (*TrafficManagementConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_d0a1188b3d395975, []int{3}
}

func (m *TrafficManagementConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TrafficManagementConfig.Unmarshal(m, b)
}
func (m *TrafficManagementConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TrafficManagementConfig.Marshal(b, m, deterministic)
}
func (m *TrafficManagementConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TrafficManagementConfig.Merge(m, src)
}
func (m *TrafficManagementConfig) XXX_Size() int {
	return xxx_messageInfo_TrafficManagementConfig.Size(m)
}
func (m *TrafficManagementConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_TrafficManagementConfig.DiscardUnknown(m)
}

var xxx_messageInfo_TrafficManagementConfig proto.InternalMessageInfo

func (m *TrafficManagementConfig) GetEnabled() bool {
	if m != nil {
		return m.Enabled
	}
	return false
}

func (m *TrafficManagementConfig) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

func (m *TrafficManagementConfig) GetAutoInjection() bool {
	if m != nil {
		return m.AutoInjection
	}
	return false
}

func (m *TrafficManagementConfig) GetPilotConfig() *PilotConfig {
	if m != nil {
		return m.PilotConfig
	}
	return nil
}

func (m *TrafficManagementConfig) GetProxyConfig() *ProxyConfig {
	if m != nil {
		return m.ProxyConfig
	}
	return nil
}

// PilotConfig defines the configuration options for pilot.
type PilotConfig struct {
	// Enables debug in pilot.
	Debug bool `protobuf:"varint,1,opt,name=debug,proto3" json:"debug,omitempty"`
	// Enables sidecar in the pilot pod.
	Sidecar bool `protobuf:"varint,2,opt,name=sidecar,proto3" json:"sidecar,omitempty"`
	// Trace sampling percentage.
	TraceSampling float32 `protobuf:"fixed32,3,opt,name=trace_sampling,json=traceSampling,proto3" json:"trace_sampling,omitempty"`
	// Passthrough to corresponding k8s settings.
	Resources           *v1.ResourceRequirements         `protobuf:"bytes,50,opt,name=resources,proto3" json:"resources,omitempty"`
	HpaSpec             *v11.HorizontalPodAutoscalerSpec `protobuf:"bytes,51,opt,name=hpa_spec,json=hpaSpec,proto3" json:"hpa_spec,omitempty"`
	PodDisruptionBudget *v1beta1.PodDisruptionBudget     `protobuf:"bytes,52,opt,name=pod_disruption_budget,json=podDisruptionBudget,proto3" json:"pod_disruption_budget,omitempty"`
	NodeSelector        *v1.NodeSelector                 `protobuf:"bytes,53,opt,name=nodeSelector,proto3" json:"nodeSelector,omitempty"`
	// Additional arguments passed to pilot discovery.
	AdditionalArgs map[string]string `protobuf:"bytes,60,rep,name=additional_args,json=additionalArgs,proto3" json:"additional_args,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	// Additional environment variables for the discovery container.
	Env map[string]string `protobuf:"bytes,70,rep,name=env,proto3" json:"env,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	// Kustomize style overrides for k8s resources in rendered manifests.
	ResourceOverride     []*Object `protobuf:"bytes,100,rep,name=resource_override,json=resourceOverride,proto3" json:"resource_override,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *PilotConfig) Reset()         { *m = PilotConfig{} }
func (m *PilotConfig) String() string { return proto.CompactTextString(m) }
func (*PilotConfig) ProtoMessage()    {}
func (*PilotConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_d0a1188b3d395975, []int{4}
}

func (m *PilotConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PilotConfig.Unmarshal(m, b)
}
func (m *PilotConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PilotConfig.Marshal(b, m, deterministic)
}
func (m *PilotConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PilotConfig.Merge(m, src)
}
func (m *PilotConfig) XXX_Size() int {
	return xxx_messageInfo_PilotConfig.Size(m)
}
func (m *PilotConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_PilotConfig.DiscardUnknown(m)
}

var xxx_messageInfo_PilotConfig proto.InternalMessageInfo

func (m *PilotConfig) GetDebug() bool {
	if m != nil {
		return m.Debug
	}
	return false
}

func (m *PilotConfig) GetSidecar() bool {
	if m != nil {
		return m.Sidecar
	}
	return false
}

func (m *PilotConfig) GetTraceSampling() float32 {
	if m != nil {
		return m.TraceSampling
	}
	return 0
}

func (m *PilotConfig) GetResources() *v1.ResourceRequirements {
	if m != nil {
		return m.Resources
	}
	return nil
}

func (m *PilotConfig) GetHpaSpec() *v11.HorizontalPodAutoscalerSpec {
	if m != nil {
		return m.HpaSpec
	}
	return nil
}

func (m *PilotConfig) GetPodDisruptionBudget() *v1beta1.PodDisruptionBudget {
	if m != nil {
		return m.PodDisruptionBudget
	}
	return nil
}

func (m *PilotConfig) GetNodeSelector() *v1.NodeSelector {
	if m != nil {
		return m.NodeSelector
	}
	return nil
}

func (m *PilotConfig) GetAdditionalArgs() map[string]string {
	if m != nil {
		return m.AdditionalArgs
	}
	return nil
}

func (m *PilotConfig) GetEnv() map[string]string {
	if m != nil {
		return m.Env
	}
	return nil
}

func (m *PilotConfig) GetResourceOverride() []*Object {
	if m != nil {
		return m.ResourceOverride
	}
	return nil
}

// ProxyConfig defines the configuration options for the injected Envoy proxy.
type ProxyConfig struct {
	// Enables debug in the proxy.
	Debug bool `protobuf:"varint,1,opt,name=debug,proto3" json:"debug,omitempty"`
	// TBD: is privileged ever set in isolation?
	Privileged bool `protobuf:"varint,2,opt,name=privileged,proto3" json:"privileged,omitempty"`
	// Enables coredump in proxy container.
	EnableCoredump   bool                         `protobuf:"varint,3,opt,name=enable_coredump,json=enableCoredump,proto3" json:"enable_coredump,omitempty"`
	InterceptionMode ProxyConfig_InterceptionMode `protobuf:"varint,4,opt,name=interception_mode,json=interceptionMode,proto3,enum=v1alpha1.ProxyConfig_InterceptionMode" json:"interception_mode,omitempty"`
	// Below settings would otherwise be implemented as a k8s overlay but because the proxy resources are defined
	// as a ConfigMap containing a second template, it's probably too difficult to override fields in the k8s
	// ConfigMap.
	StatusPort      uint32 `protobuf:"varint,5,opt,name=status_port,json=statusPort,proto3" json:"status_port,omitempty"`
	ImagePullPolicy string `protobuf:"bytes,6,opt,name=image_pull_policy,json=imagePullPolicy,proto3" json:"image_pull_policy,omitempty"`
	ProxyInitImage  string `protobuf:"bytes,7,opt,name=proxy_init_image,json=proxyInitImage,proto3" json:"proxy_init_image,omitempty"`
	// Address and port filtering.
	IncludeIpRanges     string `protobuf:"bytes,8,opt,name=include_ip_ranges,json=includeIpRanges,proto3" json:"include_ip_ranges,omitempty"`
	ExcludeIpRanges     string `protobuf:"bytes,9,opt,name=exclude_ip_ranges,json=excludeIpRanges,proto3" json:"exclude_ip_ranges,omitempty"`
	IncludeInboundPorts string `protobuf:"bytes,10,opt,name=include_inbound_ports,json=includeInboundPorts,proto3" json:"include_inbound_ports,omitempty"`
	ExcludeInboundPorts string `protobuf:"bytes,11,opt,name=exclude_inbound_ports,json=excludeInboundPorts,proto3" json:"exclude_inbound_ports,omitempty"`
	// Envoy specific timer settings.
	ConnectTimeout         string `protobuf:"bytes,12,opt,name=connect_timeout,json=connectTimeout,proto3" json:"connect_timeout,omitempty"`
	DrainDuration          string `protobuf:"bytes,13,opt,name=drain_duration,json=drainDuration,proto3" json:"drain_duration,omitempty"`
	ParentShutdownDuration string `protobuf:"bytes,14,opt,name=parent_shutdown_duration,json=parentShutdownDuration,proto3" json:"parent_shutdown_duration,omitempty"`
	Concurrency            uint32 `protobuf:"varint,15,opt,name=concurrency,proto3" json:"concurrency,omitempty"`
	ClusterDomain          string `protobuf:"bytes,16,opt,name=cluster_domain,json=clusterDomain,proto3" json:"cluster_domain,omitempty"`
	PodDnsSearchNamespaces string `protobuf:"bytes,17,opt,name=pod_dns_search_namespaces,json=podDnsSearchNamespaces,proto3" json:"pod_dns_search_namespaces,omitempty"`
	// Tracer options
	Lightstep *ProxyConfig_LightstepConfig `protobuf:"bytes,30,opt,name=lightstep,proto3" json:"lightstep,omitempty"`
	Zipkin    *ProxyConfig_ZipkinConfig    `protobuf:"bytes,31,opt,name=zipkin,proto3" json:"zipkin,omitempty"`
	// SDS settings
	Sds *SdsConfig `protobuf:"bytes,40,opt,name=sds,proto3" json:"sds,omitempty"`
	// Passthrough to k8s resources.
	ReadinessProbe *v1.Probe                `protobuf:"bytes,50,opt,name=readiness_probe,json=readinessProbe,proto3" json:"readiness_probe,omitempty"`
	Resources      *v1.ResourceRequirements `protobuf:"bytes,51,opt,name=resources,proto3" json:"resources,omitempty"`
	// Additional arguments passed to Envoy.
	AdditionalArgs map[string]string `protobuf:"bytes,60,rep,name=additional_args,json=additionalArgs,proto3" json:"additional_args,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	// Additional environment variables for the container.
	Env map[string]string `protobuf:"bytes,70,rep,name=env,proto3" json:"env,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	// Kustomize style overrides for k8s resources in rendered manifests.
	ResourceOverride     []*Object `protobuf:"bytes,100,rep,name=resource_override,json=resourceOverride,proto3" json:"resource_override,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *ProxyConfig) Reset()         { *m = ProxyConfig{} }
func (m *ProxyConfig) String() string { return proto.CompactTextString(m) }
func (*ProxyConfig) ProtoMessage()    {}
func (*ProxyConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_d0a1188b3d395975, []int{5}
}

func (m *ProxyConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProxyConfig.Unmarshal(m, b)
}
func (m *ProxyConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProxyConfig.Marshal(b, m, deterministic)
}
func (m *ProxyConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProxyConfig.Merge(m, src)
}
func (m *ProxyConfig) XXX_Size() int {
	return xxx_messageInfo_ProxyConfig.Size(m)
}
func (m *ProxyConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_ProxyConfig.DiscardUnknown(m)
}

var xxx_messageInfo_ProxyConfig proto.InternalMessageInfo

func (m *ProxyConfig) GetDebug() bool {
	if m != nil {
		return m.Debug
	}
	return false
}

func (m *ProxyConfig) GetPrivileged() bool {
	if m != nil {
		return m.Privileged
	}
	return false
}

func (m *ProxyConfig) GetEnableCoredump() bool {
	if m != nil {
		return m.EnableCoredump
	}
	return false
}

func (m *ProxyConfig) GetInterceptionMode() ProxyConfig_InterceptionMode {
	if m != nil {
		return m.InterceptionMode
	}
	return ProxyConfig_REDIRECT
}

func (m *ProxyConfig) GetStatusPort() uint32 {
	if m != nil {
		return m.StatusPort
	}
	return 0
}

func (m *ProxyConfig) GetImagePullPolicy() string {
	if m != nil {
		return m.ImagePullPolicy
	}
	return ""
}

func (m *ProxyConfig) GetProxyInitImage() string {
	if m != nil {
		return m.ProxyInitImage
	}
	return ""
}

func (m *ProxyConfig) GetIncludeIpRanges() string {
	if m != nil {
		return m.IncludeIpRanges
	}
	return ""
}

func (m *ProxyConfig) GetExcludeIpRanges() string {
	if m != nil {
		return m.ExcludeIpRanges
	}
	return ""
}

func (m *ProxyConfig) GetIncludeInboundPorts() string {
	if m != nil {
		return m.IncludeInboundPorts
	}
	return ""
}

func (m *ProxyConfig) GetExcludeInboundPorts() string {
	if m != nil {
		return m.ExcludeInboundPorts
	}
	return ""
}

func (m *ProxyConfig) GetConnectTimeout() string {
	if m != nil {
		return m.ConnectTimeout
	}
	return ""
}

func (m *ProxyConfig) GetDrainDuration() string {
	if m != nil {
		return m.DrainDuration
	}
	return ""
}

func (m *ProxyConfig) GetParentShutdownDuration() string {
	if m != nil {
		return m.ParentShutdownDuration
	}
	return ""
}

func (m *ProxyConfig) GetConcurrency() uint32 {
	if m != nil {
		return m.Concurrency
	}
	return 0
}

func (m *ProxyConfig) GetClusterDomain() string {
	if m != nil {
		return m.ClusterDomain
	}
	return ""
}

func (m *ProxyConfig) GetPodDnsSearchNamespaces() string {
	if m != nil {
		return m.PodDnsSearchNamespaces
	}
	return ""
}

func (m *ProxyConfig) GetLightstep() *ProxyConfig_LightstepConfig {
	if m != nil {
		return m.Lightstep
	}
	return nil
}

func (m *ProxyConfig) GetZipkin() *ProxyConfig_ZipkinConfig {
	if m != nil {
		return m.Zipkin
	}
	return nil
}

func (m *ProxyConfig) GetSds() *SdsConfig {
	if m != nil {
		return m.Sds
	}
	return nil
}

func (m *ProxyConfig) GetReadinessProbe() *v1.Probe {
	if m != nil {
		return m.ReadinessProbe
	}
	return nil
}

func (m *ProxyConfig) GetResources() *v1.ResourceRequirements {
	if m != nil {
		return m.Resources
	}
	return nil
}

func (m *ProxyConfig) GetAdditionalArgs() map[string]string {
	if m != nil {
		return m.AdditionalArgs
	}
	return nil
}

func (m *ProxyConfig) GetEnv() map[string]string {
	if m != nil {
		return m.Env
	}
	return nil
}

func (m *ProxyConfig) GetResourceOverride() []*Object {
	if m != nil {
		return m.ResourceOverride
	}
	return nil
}

// Tracer config options.
type ProxyConfig_LightstepConfig struct {
	Address              string   `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	AccessToken          string   `protobuf:"bytes,2,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	CaCertPath           string   `protobuf:"bytes,3,opt,name=ca_cert_path,json=caCertPath,proto3" json:"ca_cert_path,omitempty"`
	Secure               bool     `protobuf:"varint,4,opt,name=secure,proto3" json:"secure,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProxyConfig_LightstepConfig) Reset()         { *m = ProxyConfig_LightstepConfig{} }
func (m *ProxyConfig_LightstepConfig) String() string { return proto.CompactTextString(m) }
func (*ProxyConfig_LightstepConfig) ProtoMessage()    {}
func (*ProxyConfig_LightstepConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_d0a1188b3d395975, []int{5, 0}
}

func (m *ProxyConfig_LightstepConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProxyConfig_LightstepConfig.Unmarshal(m, b)
}
func (m *ProxyConfig_LightstepConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProxyConfig_LightstepConfig.Marshal(b, m, deterministic)
}
func (m *ProxyConfig_LightstepConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProxyConfig_LightstepConfig.Merge(m, src)
}
func (m *ProxyConfig_LightstepConfig) XXX_Size() int {
	return xxx_messageInfo_ProxyConfig_LightstepConfig.Size(m)
}
func (m *ProxyConfig_LightstepConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_ProxyConfig_LightstepConfig.DiscardUnknown(m)
}

var xxx_messageInfo_ProxyConfig_LightstepConfig proto.InternalMessageInfo

func (m *ProxyConfig_LightstepConfig) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *ProxyConfig_LightstepConfig) GetAccessToken() string {
	if m != nil {
		return m.AccessToken
	}
	return ""
}

func (m *ProxyConfig_LightstepConfig) GetCaCertPath() string {
	if m != nil {
		return m.CaCertPath
	}
	return ""
}

func (m *ProxyConfig_LightstepConfig) GetSecure() bool {
	if m != nil {
		return m.Secure
	}
	return false
}

type ProxyConfig_ZipkinConfig struct {
	Address              string   `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProxyConfig_ZipkinConfig) Reset()         { *m = ProxyConfig_ZipkinConfig{} }
func (m *ProxyConfig_ZipkinConfig) String() string { return proto.CompactTextString(m) }
func (*ProxyConfig_ZipkinConfig) ProtoMessage()    {}
func (*ProxyConfig_ZipkinConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_d0a1188b3d395975, []int{5, 1}
}

func (m *ProxyConfig_ZipkinConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProxyConfig_ZipkinConfig.Unmarshal(m, b)
}
func (m *ProxyConfig_ZipkinConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProxyConfig_ZipkinConfig.Marshal(b, m, deterministic)
}
func (m *ProxyConfig_ZipkinConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProxyConfig_ZipkinConfig.Merge(m, src)
}
func (m *ProxyConfig_ZipkinConfig) XXX_Size() int {
	return xxx_messageInfo_ProxyConfig_ZipkinConfig.Size(m)
}
func (m *ProxyConfig_ZipkinConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_ProxyConfig_ZipkinConfig.DiscardUnknown(m)
}

var xxx_messageInfo_ProxyConfig_ZipkinConfig proto.InternalMessageInfo

func (m *ProxyConfig_ZipkinConfig) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

type PolicyConfig struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PolicyConfig) Reset()         { *m = PolicyConfig{} }
func (m *PolicyConfig) String() string { return proto.CompactTextString(m) }
func (*PolicyConfig) ProtoMessage()    {}
func (*PolicyConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_d0a1188b3d395975, []int{6}
}

func (m *PolicyConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PolicyConfig.Unmarshal(m, b)
}
func (m *PolicyConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PolicyConfig.Marshal(b, m, deterministic)
}
func (m *PolicyConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PolicyConfig.Merge(m, src)
}
func (m *PolicyConfig) XXX_Size() int {
	return xxx_messageInfo_PolicyConfig.Size(m)
}
func (m *PolicyConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_PolicyConfig.DiscardUnknown(m)
}

var xxx_messageInfo_PolicyConfig proto.InternalMessageInfo

type TelemetryConfig struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TelemetryConfig) Reset()         { *m = TelemetryConfig{} }
func (m *TelemetryConfig) String() string { return proto.CompactTextString(m) }
func (*TelemetryConfig) ProtoMessage()    {}
func (*TelemetryConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_d0a1188b3d395975, []int{7}
}

func (m *TelemetryConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TelemetryConfig.Unmarshal(m, b)
}
func (m *TelemetryConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TelemetryConfig.Marshal(b, m, deterministic)
}
func (m *TelemetryConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TelemetryConfig.Merge(m, src)
}
func (m *TelemetryConfig) XXX_Size() int {
	return xxx_messageInfo_TelemetryConfig.Size(m)
}
func (m *TelemetryConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_TelemetryConfig.DiscardUnknown(m)
}

var xxx_messageInfo_TelemetryConfig proto.InternalMessageInfo

type SecurityConfig struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SecurityConfig) Reset()         { *m = SecurityConfig{} }
func (m *SecurityConfig) String() string { return proto.CompactTextString(m) }
func (*SecurityConfig) ProtoMessage()    {}
func (*SecurityConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_d0a1188b3d395975, []int{8}
}

func (m *SecurityConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SecurityConfig.Unmarshal(m, b)
}
func (m *SecurityConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SecurityConfig.Marshal(b, m, deterministic)
}
func (m *SecurityConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SecurityConfig.Merge(m, src)
}
func (m *SecurityConfig) XXX_Size() int {
	return xxx_messageInfo_SecurityConfig.Size(m)
}
func (m *SecurityConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_SecurityConfig.DiscardUnknown(m)
}

var xxx_messageInfo_SecurityConfig proto.InternalMessageInfo

type ConfigManagementConfig struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConfigManagementConfig) Reset()         { *m = ConfigManagementConfig{} }
func (m *ConfigManagementConfig) String() string { return proto.CompactTextString(m) }
func (*ConfigManagementConfig) ProtoMessage()    {}
func (*ConfigManagementConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_d0a1188b3d395975, []int{9}
}

func (m *ConfigManagementConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConfigManagementConfig.Unmarshal(m, b)
}
func (m *ConfigManagementConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConfigManagementConfig.Marshal(b, m, deterministic)
}
func (m *ConfigManagementConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfigManagementConfig.Merge(m, src)
}
func (m *ConfigManagementConfig) XXX_Size() int {
	return xxx_messageInfo_ConfigManagementConfig.Size(m)
}
func (m *ConfigManagementConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfigManagementConfig.DiscardUnknown(m)
}

var xxx_messageInfo_ConfigManagementConfig proto.InternalMessageInfo

type IngressGatewayConfig struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IngressGatewayConfig) Reset()         { *m = IngressGatewayConfig{} }
func (m *IngressGatewayConfig) String() string { return proto.CompactTextString(m) }
func (*IngressGatewayConfig) ProtoMessage()    {}
func (*IngressGatewayConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_d0a1188b3d395975, []int{10}
}

func (m *IngressGatewayConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IngressGatewayConfig.Unmarshal(m, b)
}
func (m *IngressGatewayConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IngressGatewayConfig.Marshal(b, m, deterministic)
}
func (m *IngressGatewayConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IngressGatewayConfig.Merge(m, src)
}
func (m *IngressGatewayConfig) XXX_Size() int {
	return xxx_messageInfo_IngressGatewayConfig.Size(m)
}
func (m *IngressGatewayConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_IngressGatewayConfig.DiscardUnknown(m)
}

var xxx_messageInfo_IngressGatewayConfig proto.InternalMessageInfo

type EgressGatewayConfig struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EgressGatewayConfig) Reset()         { *m = EgressGatewayConfig{} }
func (m *EgressGatewayConfig) String() string { return proto.CompactTextString(m) }
func (*EgressGatewayConfig) ProtoMessage()    {}
func (*EgressGatewayConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_d0a1188b3d395975, []int{11}
}

func (m *EgressGatewayConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EgressGatewayConfig.Unmarshal(m, b)
}
func (m *EgressGatewayConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EgressGatewayConfig.Marshal(b, m, deterministic)
}
func (m *EgressGatewayConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EgressGatewayConfig.Merge(m, src)
}
func (m *EgressGatewayConfig) XXX_Size() int {
	return xxx_messageInfo_EgressGatewayConfig.Size(m)
}
func (m *EgressGatewayConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_EgressGatewayConfig.DiscardUnknown(m)
}

var xxx_messageInfo_EgressGatewayConfig proto.InternalMessageInfo

// OperatorConfig defines a config used to install an external operator.
type OperatorConfig struct {
	// manifest_path is the URL for the operator install manifest.
	ManifestPath string `protobuf:"bytes,1,opt,name=manifest_path,json=manifestPath,proto3" json:"manifest_path,omitempty"`
	// namespace is the namespace the operator manifest and CR are installed into.
	Namespace string `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	// spec is the initial CR for the operator.
	Spec                 *Object  `protobuf:"bytes,3,opt,name=spec,proto3" json:"spec,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OperatorConfig) Reset()         { *m = OperatorConfig{} }
func (m *OperatorConfig) String() string { return proto.CompactTextString(m) }
func (*OperatorConfig) ProtoMessage()    {}
func (*OperatorConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_d0a1188b3d395975, []int{12}
}

func (m *OperatorConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OperatorConfig.Unmarshal(m, b)
}
func (m *OperatorConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OperatorConfig.Marshal(b, m, deterministic)
}
func (m *OperatorConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OperatorConfig.Merge(m, src)
}
func (m *OperatorConfig) XXX_Size() int {
	return xxx_messageInfo_OperatorConfig.Size(m)
}
func (m *OperatorConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_OperatorConfig.DiscardUnknown(m)
}

var xxx_messageInfo_OperatorConfig proto.InternalMessageInfo

func (m *OperatorConfig) GetManifestPath() string {
	if m != nil {
		return m.ManifestPath
	}
	return ""
}

func (m *OperatorConfig) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

func (m *OperatorConfig) GetSpec() *Object {
	if m != nil {
		return m.Spec
	}
	return nil
}

type IstioInstaller struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec                 *InstallerSpec   `protobuf:"bytes,3,opt,name=spec,proto3" json:"spec,omitempty"`
	Status               *InstallerStatus `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *IstioInstaller) Reset()         { *m = IstioInstaller{} }
func (m *IstioInstaller) String() string { return proto.CompactTextString(m) }
func (*IstioInstaller) ProtoMessage()    {}
func (*IstioInstaller) Descriptor() ([]byte, []int) {
	return fileDescriptor_d0a1188b3d395975, []int{13}
}

func (m *IstioInstaller) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IstioInstaller.Unmarshal(m, b)
}
func (m *IstioInstaller) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IstioInstaller.Marshal(b, m, deterministic)
}
func (m *IstioInstaller) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IstioInstaller.Merge(m, src)
}
func (m *IstioInstaller) XXX_Size() int {
	return xxx_messageInfo_IstioInstaller.Size(m)
}
func (m *IstioInstaller) XXX_DiscardUnknown() {
	xxx_messageInfo_IstioInstaller.DiscardUnknown(m)
}

var xxx_messageInfo_IstioInstaller proto.InternalMessageInfo

func (m *IstioInstaller) GetSpec() *InstallerSpec {
	if m != nil {
		return m.Spec
	}
	return nil
}

func (m *IstioInstaller) GetStatus() *InstallerStatus {
	if m != nil {
		return m.Status
	}
	return nil
}

type Object struct {
	Metadata             *v12.ObjectMeta       `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Data                 *runtime.RawExtension `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *Object) Reset()         { *m = Object{} }
func (m *Object) String() string { return proto.CompactTextString(m) }
func (*Object) ProtoMessage()    {}
func (*Object) Descriptor() ([]byte, []int) {
	return fileDescriptor_d0a1188b3d395975, []int{14}
}

func (m *Object) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Object.Unmarshal(m, b)
}
func (m *Object) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Object.Marshal(b, m, deterministic)
}
func (m *Object) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Object.Merge(m, src)
}
func (m *Object) XXX_Size() int {
	return xxx_messageInfo_Object.Size(m)
}
func (m *Object) XXX_DiscardUnknown() {
	xxx_messageInfo_Object.DiscardUnknown(m)
}

var xxx_messageInfo_Object proto.InternalMessageInfo

func (m *Object) GetMetadata() *v12.ObjectMeta {
	if m != nil {
		return m.Metadata
	}
	return nil
}

func (m *Object) GetData() *runtime.RawExtension {
	if m != nil {
		return m.Data
	}
	return nil
}

// FIXME: this should be moved out
type SdsConfig struct {
	Enabled              bool     `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	UdsPath              string   `protobuf:"bytes,2,opt,name=uds_path,json=udsPath,proto3" json:"uds_path,omitempty"`
	UseTrustworthyJwt    bool     `protobuf:"varint,3,opt,name=use_trustworthy_jwt,json=useTrustworthyJwt,proto3" json:"use_trustworthy_jwt,omitempty"`
	UseNormalJwt         bool     `protobuf:"varint,4,opt,name=use_normal_jwt,json=useNormalJwt,proto3" json:"use_normal_jwt,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SdsConfig) Reset()         { *m = SdsConfig{} }
func (m *SdsConfig) String() string { return proto.CompactTextString(m) }
func (*SdsConfig) ProtoMessage()    {}
func (*SdsConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_d0a1188b3d395975, []int{15}
}

func (m *SdsConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SdsConfig.Unmarshal(m, b)
}
func (m *SdsConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SdsConfig.Marshal(b, m, deterministic)
}
func (m *SdsConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SdsConfig.Merge(m, src)
}
func (m *SdsConfig) XXX_Size() int {
	return xxx_messageInfo_SdsConfig.Size(m)
}
func (m *SdsConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_SdsConfig.DiscardUnknown(m)
}

var xxx_messageInfo_SdsConfig proto.InternalMessageInfo

func (m *SdsConfig) GetEnabled() bool {
	if m != nil {
		return m.Enabled
	}
	return false
}

func (m *SdsConfig) GetUdsPath() string {
	if m != nil {
		return m.UdsPath
	}
	return ""
}

func (m *SdsConfig) GetUseTrustworthyJwt() bool {
	if m != nil {
		return m.UseTrustworthyJwt
	}
	return false
}

func (m *SdsConfig) GetUseNormalJwt() bool {
	if m != nil {
		return m.UseNormalJwt
	}
	return false
}

func init() {
	proto.RegisterEnum("v1alpha1.ProxyConfig_InterceptionMode", ProxyConfig_InterceptionMode_name, ProxyConfig_InterceptionMode_value)
	proto.RegisterType((*InstallerSpec)(nil), "v1alpha1.InstallerSpec")
	proto.RegisterType((*InstallerStatus)(nil), "v1alpha1.InstallerStatus")
	proto.RegisterType((*RemoteClusterConfig)(nil), "v1alpha1.RemoteClusterConfig")
	proto.RegisterType((*TrafficManagementConfig)(nil), "v1alpha1.TrafficManagementConfig")
	proto.RegisterType((*PilotConfig)(nil), "v1alpha1.PilotConfig")
	proto.RegisterMapType((map[string]string)(nil), "v1alpha1.PilotConfig.AdditionalArgsEntry")
	proto.RegisterMapType((map[string]string)(nil), "v1alpha1.PilotConfig.EnvEntry")
	proto.RegisterType((*ProxyConfig)(nil), "v1alpha1.ProxyConfig")
	proto.RegisterMapType((map[string]string)(nil), "v1alpha1.ProxyConfig.AdditionalArgsEntry")
	proto.RegisterMapType((map[string]string)(nil), "v1alpha1.ProxyConfig.EnvEntry")
	proto.RegisterType((*ProxyConfig_LightstepConfig)(nil), "v1alpha1.ProxyConfig.LightstepConfig")
	proto.RegisterType((*ProxyConfig_ZipkinConfig)(nil), "v1alpha1.ProxyConfig.ZipkinConfig")
	proto.RegisterType((*PolicyConfig)(nil), "v1alpha1.PolicyConfig")
	proto.RegisterType((*TelemetryConfig)(nil), "v1alpha1.TelemetryConfig")
	proto.RegisterType((*SecurityConfig)(nil), "v1alpha1.SecurityConfig")
	proto.RegisterType((*ConfigManagementConfig)(nil), "v1alpha1.ConfigManagementConfig")
	proto.RegisterType((*IngressGatewayConfig)(nil), "v1alpha1.IngressGatewayConfig")
	proto.RegisterType((*EgressGatewayConfig)(nil), "v1alpha1.EgressGatewayConfig")
	proto.RegisterType((*OperatorConfig)(nil), "v1alpha1.OperatorConfig")
	proto.RegisterType((*IstioInstaller)(nil), "v1alpha1.IstioInstaller")
	proto.RegisterType((*Object)(nil), "v1alpha1.Object")
	proto.RegisterType((*SdsConfig)(nil), "v1alpha1.SdsConfig")
}

func init() { proto.RegisterFile("istioinstaller_types.proto", fileDescriptor_d0a1188b3d395975) }

var fileDescriptor_d0a1188b3d395975 = []byte{
	// 1792 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xc4, 0x58, 0xdd, 0x72, 0x1b, 0x49,
	0x15, 0x46, 0x71, 0xe2, 0xc8, 0x47, 0xb2, 0x2c, 0xb7, 0x63, 0x67, 0xe2, 0x82, 0xc4, 0x2b, 0x36,
	0xe0, 0xb0, 0x30, 0x8e, 0x9d, 0xb0, 0x84, 0x2d, 0xb8, 0xf0, 0xda, 0xde, 0xa0, 0xad, 0x4d, 0xa2,
	0x1d, 0xfb, 0x02, 0xb8, 0x99, 0x6a, 0xcd, 0x1c, 0x8f, 0x7a, 0x3d, 0xea, 0x1e, 0xba, 0x7b, 0xec,
	0x68, 0x9f, 0x80, 0x0b, 0xae, 0xa9, 0xe2, 0x05, 0x78, 0x2b, 0x1e, 0x80, 0x2a, 0x1e, 0x82, 0xea,
	0x9f, 0x91, 0x46, 0xb6, 0x9c, 0x5a, 0x16, 0xaa, 0xb8, 0xf3, 0x7c, 0xe7, 0xfb, 0x3e, 0xf5, 0xdf,
	0x39, 0x7d, 0xda, 0xb0, 0xcd, 0x94, 0x66, 0x82, 0x71, 0xa5, 0x69, 0x9e, 0xa3, 0x8c, 0xf5, 0xa4,
	0x40, 0x15, 0x16, 0x52, 0x68, 0x41, 0x9a, 0x97, 0xfb, 0x34, 0x2f, 0x46, 0x74, 0x7f, 0xbb, 0x77,
	0xf1, 0x4a, 0x85, 0x4c, 0xec, 0xd1, 0x82, 0xed, 0x25, 0x42, 0xe2, 0xde, 0xe5, 0xfe, 0x5e, 0x86,
	0x1c, 0x25, 0xd5, 0x98, 0x3a, 0xf6, 0xf6, 0xb3, 0x1a, 0xa7, 0x10, 0x39, 0x4b, 0x26, 0x7b, 0x97,
	0xfb, 0x43, 0xd4, 0xf4, 0xc3, 0x54, 0x5a, 0x6a, 0xa1, 0x12, 0x9a, 0x33, 0x9e, 0x2d, 0x72, 0x7d,
	0x39, 0xa3, 0x8e, 0x69, 0x32, 0x62, 0x1c, 0xe5, 0x64, 0xaf, 0xb8, 0xc8, 0x0c, 0xa0, 0xf6, 0xc6,
	0xa8, 0xe9, 0x22, 0xd5, 0xde, 0x6d, 0x2a, 0x59, 0x72, 0xcd, 0xc6, 0x78, 0x5d, 0xd0, 0xfb, 0xfb,
	0x32, 0xac, 0xf6, 0xab, 0x45, 0x38, 0x2d, 0x30, 0x21, 0xcf, 0xe1, 0x81, 0x5f, 0x95, 0xb8, 0xa0,
	0xc9, 0x05, 0xcd, 0x30, 0x2e, 0xa8, 0x1e, 0x05, 0x8d, 0x9d, 0xc6, 0xee, 0x4a, 0x44, 0x7c, 0x6c,
	0xe0, 0x42, 0x03, 0xaa, 0x47, 0xe4, 0xa7, 0xb0, 0x96, 0x08, 0xae, 0xa5, 0xb0, 0x0b, 0xc9, 0xe9,
	0x18, 0x83, 0x3b, 0x96, 0xdc, 0x99, 0xc1, 0x6f, 0xe9, 0x18, 0x49, 0x17, 0x96, 0x46, 0xe5, 0x30,
	0x58, 0xb2, 0x41, 0xf3, 0xa7, 0x41, 0x34, 0xcd, 0x82, 0xbb, 0x0e, 0xd1, 0x34, 0x23, 0x9f, 0xc0,
	0x7a, 0x8a, 0xe7, 0xb4, 0xcc, 0xb5, 0x75, 0x52, 0x05, 0x4d, 0x30, 0xb8, 0x67, 0xe3, 0x5d, 0x1f,
	0x78, 0x5b, 0xe1, 0xe4, 0x6b, 0xd8, 0x94, 0x38, 0x16, 0x1a, 0xe3, 0x24, 0x2f, 0x95, 0x46, 0x19,
	0x27, 0x82, 0x9f, 0xb3, 0x2c, 0x80, 0x9d, 0xc6, 0x6e, 0xeb, 0xe0, 0x47, 0x61, 0xb5, 0x91, 0x61,
	0x64, 0x69, 0x47, 0x8e, 0x75, 0x64, 0x49, 0xd1, 0x86, 0xbc, 0x09, 0x92, 0x01, 0x10, 0x2d, 0xe9,
	0xf9, 0x39, 0x4b, 0xe2, 0x31, 0xe5, 0x34, 0xc3, 0x31, 0x72, 0x1d, 0x3c, 0xb0, 0x7e, 0x1f, 0xcd,
	0xfc, 0xce, 0x1c, 0xe7, 0xcd, 0x94, 0xe2, 0x3d, 0xd7, 0xf5, 0xf5, 0x00, 0x09, 0x61, 0xd9, 0x1d,
	0x8b, 0x60, 0xd3, 0xba, 0x6c, 0xcd, 0x5c, 0x06, 0x16, 0xf7, 0x52, 0xcf, 0x22, 0xbf, 0x82, 0x15,
	0x8d, 0x39, 0x8e, 0x51, 0xcb, 0x49, 0xb0, 0x65, 0x25, 0x8f, 0x6a, 0x3f, 0x5c, 0x85, 0xbc, 0x6a,
	0xc6, 0x25, 0x2f, 0xa1, 0xa9, 0x30, 0x29, 0x25, 0xd3, 0x93, 0xe0, 0xa1, 0xd5, 0x05, 0x33, 0xdd,
	0xa9, 0x8f, 0x78, 0xd9, 0x94, 0x49, 0xde, 0xc0, 0xba, 0x5b, 0xb4, 0xfa, 0x7c, 0x03, 0x2b, 0xdf,
	0x99, 0xc9, 0x9d, 0xec, 0xc6, 0x74, 0xbb, 0xc9, 0x35, 0x9c, 0xbc, 0x86, 0x35, 0xc6, 0x33, 0x89,
	0x4a, 0xc5, 0x19, 0xd5, 0x78, 0x45, 0x27, 0xc1, 0xe3, 0x9d, 0xa5, 0xdd, 0xd6, 0xc1, 0xe3, 0x99,
	0x59, 0xdf, 0x11, 0x5e, 0xbb, 0xb8, 0xb7, 0xea, 0xb0, 0x39, 0x94, 0x1c, 0x43, 0x07, 0xe7, 0x7d,
	0x9e, 0x58, 0x9f, 0xda, 0xa6, 0x9e, 0x2c, 0xb0, 0x59, 0xc5, 0x39, 0x97, 0xd7, 0x40, 0xf0, 0xbd,
	0x46, 0xc9, 0x69, 0x1e, 0x8b, 0xc2, 0x1c, 0x7d, 0x21, 0x55, 0x70, 0x60, 0x9d, 0x6a, 0xab, 0xf3,
	0xce, 0x87, 0xaa, 0x5d, 0xac, 0x34, 0x15, 0xae, 0x7a, 0x14, 0xd6, 0x66, 0x79, 0xa2, 0xa9, 0x2e,
	0x15, 0xf9, 0x31, 0xac, 0x16, 0x52, 0xbc, 0x9f, 0xc4, 0xfe, 0x98, 0xfb, 0x14, 0x69, 0x5b, 0xf0,
	0xc8, 0x61, 0xe4, 0x19, 0x74, 0x15, 0x4b, 0x31, 0xa1, 0x32, 0x66, 0xfc, 0x1b, 0x4c, 0xb4, 0x90,
	0x3e, 0x3b, 0xd6, 0x3c, 0xde, 0xf7, 0x70, 0xef, 0x2f, 0x0d, 0xd8, 0x58, 0x70, 0x4e, 0x49, 0x00,
	0xf7, 0x91, 0xd3, 0x61, 0x8e, 0xa9, 0xfd, 0x85, 0x66, 0x54, 0x7d, 0x92, 0x1f, 0xc2, 0xca, 0x2c,
	0x49, 0x9c, 0xeb, 0x0c, 0x20, 0xbf, 0x85, 0x75, 0x89, 0x4a, 0x94, 0x32, 0xc1, 0x58, 0x5c, 0xa2,
	0x94, 0x2c, 0xc5, 0x60, 0xc9, 0x4e, 0xbd, 0x5b, 0x9b, 0xfa, 0xd0, 0xfc, 0x7c, 0xd4, 0xad, 0xa8,
	0xef, 0x3c, 0xb3, 0xf7, 0xaf, 0x06, 0x3c, 0xbc, 0xe5, 0x98, 0x7f, 0xef, 0x21, 0x3d, 0x85, 0x8e,
	0xa9, 0x7b, 0x7e, 0x29, 0x98, 0xe0, 0xb6, 0x18, 0x34, 0xa3, 0x55, 0x83, 0xf6, 0x2b, 0x90, 0xbc,
	0x82, 0x76, 0xc1, 0x72, 0xa1, 0xab, 0x74, 0xbe, 0x6b, 0x8f, 0xe3, 0x66, 0x2d, 0x71, 0x4c, 0xd4,
	0x6f, 0x56, 0xab, 0x98, 0x7d, 0x58, 0x65, 0xb5, 0x27, 0x46, 0x79, 0xef, 0x86, 0xd2, 0x6f, 0x8e,
	0x53, 0xce, 0x3e, 0x7a, 0xff, 0xbc, 0x07, 0xad, 0x9a, 0x2d, 0x79, 0x00, 0xf7, 0x52, 0x1c, 0x96,
	0x99, 0x9f, 0xa0, 0xfb, 0x30, 0x13, 0xf7, 0xdb, 0x66, 0x27, 0xd7, 0x8c, 0xaa, 0x4f, 0x33, 0x35,
	0x2d, 0x69, 0x82, 0xb1, 0xa2, 0xe3, 0xc2, 0x54, 0x75, 0x3b, 0xb5, 0x3b, 0xd1, 0xaa, 0x45, 0x4f,
	0x3d, 0x48, 0xbe, 0x80, 0x95, 0x6a, 0xa5, 0xcd, 0x39, 0x34, 0xa3, 0xdb, 0x0d, 0x5d, 0xd5, 0x0e,
	0x69, 0xc1, 0x42, 0x73, 0xcb, 0x84, 0x97, 0xa6, 0x60, 0x39, 0x52, 0x84, 0x7f, 0x2a, 0x99, 0xb4,
	0x6b, 0xaf, 0xa2, 0x99, 0x94, 0x7c, 0x0d, 0xcd, 0x51, 0x41, 0x63, 0x55, 0x60, 0x12, 0xbc, 0xb0,
	0x36, 0x9f, 0xd6, 0x6d, 0x6a, 0xb7, 0x8b, 0x71, 0xfb, 0x9d, 0x90, 0xec, 0x5b, 0xc1, 0x35, 0xcd,
	0x07, 0x22, 0x3d, 0xf4, 0x31, 0x57, 0xf0, 0xa3, 0xfb, 0xa3, 0x82, 0xda, 0xca, 0x3f, 0x84, 0xcd,
	0x42, 0xa4, 0x71, 0xca, 0x94, 0x2c, 0x0b, 0xb3, 0x0f, 0xf1, 0xb0, 0x4c, 0x33, 0xd4, 0xc1, 0x4b,
	0xeb, 0x1f, 0xd6, 0xfd, 0x5d, 0xad, 0x0a, 0xfd, 0x45, 0x17, 0x0e, 0x44, 0x7a, 0x3c, 0x95, 0x7d,
	0x6e, 0x55, 0xd1, 0x46, 0x71, 0x13, 0x24, 0xc7, 0xd0, 0xe6, 0x22, 0xc5, 0x53, 0xcc, 0x5d, 0x2a,
	0xfc, 0xd2, 0x17, 0x9a, 0x05, 0x2b, 0xf0, 0xb6, 0xc6, 0x8b, 0xe6, 0x54, 0x24, 0x82, 0x35, 0x9a,
	0xa6, 0xcc, 0xf8, 0xd2, 0x3c, 0xa6, 0x32, 0x53, 0xc1, 0x6f, 0xec, 0xb9, 0x7e, 0xb6, 0xf0, 0x88,
	0x84, 0x87, 0x53, 0xf2, 0xa1, 0xcc, 0xd4, 0x09, 0xd7, 0x72, 0x12, 0x75, 0xe8, 0x1c, 0x48, 0x9e,
	0xc3, 0x12, 0xf2, 0xcb, 0xe0, 0x8b, 0xeb, 0xc5, 0xaa, 0xee, 0x73, 0xc2, 0x2f, 0x9d, 0xd8, 0x50,
	0x17, 0xe7, 0x57, 0xfa, 0x5d, 0xf3, 0x6b, 0xfb, 0x10, 0x36, 0x16, 0x8c, 0xcb, 0x5c, 0x89, 0x17,
	0x38, 0xf1, 0xb5, 0xc4, 0xfc, 0x69, 0x4e, 0xe2, 0x25, 0xcd, 0xcb, 0x2a, 0x9d, 0xdc, 0xc7, 0x67,
	0x77, 0x5e, 0x35, 0xb6, 0x3f, 0x85, 0x66, 0x35, 0xa4, 0xff, 0x44, 0xd7, 0xfb, 0x47, 0x1b, 0x5a,
	0xb5, 0x44, 0xb8, 0xe5, 0xac, 0x3f, 0x06, 0x28, 0x24, 0xbb, 0x64, 0x39, 0x66, 0x98, 0xfa, 0xe3,
	0x5e, 0x43, 0xcc, 0xbd, 0xef, 0xb2, 0x3e, 0x36, 0x5b, 0x96, 0x96, 0xe3, 0xc2, 0x67, 0x73, 0xc7,
	0xc1, 0x47, 0x1e, 0x25, 0xa7, 0xb0, 0xce, 0xb8, 0x46, 0x99, 0xa0, 0x3b, 0x56, 0x63, 0x91, 0xa2,
	0xcd, 0xe9, 0xce, 0xc1, 0x4f, 0x16, 0x66, 0x66, 0xd8, 0xaf, 0xd1, 0xdf, 0x88, 0x14, 0xa3, 0x2e,
	0xbb, 0x86, 0x90, 0x27, 0xd0, 0x52, 0xb6, 0x0e, 0xc7, 0x85, 0x90, 0xda, 0x26, 0xfa, 0x6a, 0x04,
	0x0e, 0x1a, 0x08, 0xa9, 0xc9, 0xcf, 0x60, 0x9d, 0x8d, 0x6d, 0xfb, 0x52, 0x9a, 0x5e, 0xc6, 0x5d,
	0xc1, 0xcb, 0xae, 0xf4, 0xda, 0xc0, 0xa0, 0xcc, 0x73, 0x77, 0x03, 0x93, 0x5d, 0xe8, 0xba, 0xb2,
	0xc1, 0x38, 0xd3, 0xb1, 0x8d, 0x06, 0xf7, 0x5d, 0x0f, 0x63, 0xf1, 0x3e, 0x67, 0xba, 0x6f, 0x50,
	0xeb, 0xca, 0x93, 0xbc, 0x4c, 0x31, 0x66, 0x45, 0x2c, 0x29, 0xcf, 0x50, 0x05, 0x4d, 0xef, 0xea,
	0x02, 0xfd, 0x22, 0xb2, 0xb0, 0xe1, 0xe2, 0xfb, 0xeb, 0xdc, 0x15, 0xc7, 0xf5, 0x81, 0x29, 0xf7,
	0x00, 0x36, 0xa7, 0xbe, 0x7c, 0x28, 0x4a, 0x9e, 0xda, 0x79, 0x29, 0xdb, 0xca, 0xac, 0x44, 0x1b,
	0x95, 0xb7, 0x8b, 0x99, 0x09, 0x5a, 0xcd, 0xd4, 0x7f, 0x4e, 0xd3, 0x72, 0x9a, 0xea, 0x37, 0xea,
	0x1a, 0xd7, 0xac, 0x71, 0x4c, 0x74, 0x6c, 0x1a, 0x42, 0x51, 0xea, 0xa0, 0x3d, 0x6d, 0xd6, 0x0c,
	0x7c, 0xe6, 0x50, 0x53, 0xcf, 0x52, 0x49, 0x19, 0x8f, 0xd3, 0x52, 0x52, 0x5b, 0xaa, 0x57, 0x2d,
	0x6f, 0xd5, 0xa2, 0xc7, 0x1e, 0x24, 0xaf, 0x20, 0x28, 0xa8, 0x44, 0xae, 0x63, 0x35, 0x2a, 0x75,
	0x2a, 0xae, 0x6a, 0x82, 0x8e, 0x15, 0x6c, 0xb9, 0xf8, 0xa9, 0x0f, 0x4f, 0x95, 0x3b, 0xd0, 0x4a,
	0x04, 0x4f, 0x4a, 0x29, 0x91, 0x27, 0x93, 0x60, 0xcd, 0x6e, 0x60, 0x1d, 0x32, 0x43, 0xa8, 0xfa,
	0xba, 0x54, 0x8c, 0x29, 0xe3, 0x41, 0xd7, 0x0d, 0xc1, 0xa3, 0xc7, 0x16, 0x24, 0xbf, 0x86, 0x47,
	0xb6, 0x6e, 0x71, 0x15, 0x2b, 0xa4, 0x32, 0x19, 0xcd, 0x3a, 0x47, 0x15, 0xac, 0xfb, 0x31, 0x88,
	0xf4, 0x98, 0xab, 0x53, 0x1b, 0x9e, 0xf6, 0x8f, 0x8a, 0x1c, 0xc1, 0x4a, 0xce, 0xb2, 0x91, 0x56,
	0x1a, 0x8b, 0xe0, 0xb1, 0xad, 0x45, 0x4f, 0x17, 0x9f, 0xc8, 0xaf, 0x2a, 0x5a, 0xd5, 0x77, 0x4d,
	0x75, 0xe4, 0x33, 0x58, 0xfe, 0x96, 0x15, 0x17, 0x8c, 0x07, 0x4f, 0xac, 0x43, 0x6f, 0xb1, 0xc3,
	0x1f, 0x2d, 0xa7, 0x6a, 0xf6, 0x9c, 0x82, 0x3c, 0x85, 0x25, 0x95, 0xaa, 0x60, 0xd7, 0x0a, 0x37,
	0x6a, 0xed, 0x5a, 0xaa, 0x3c, 0xd3, 0xc4, 0xc9, 0xe7, 0xb0, 0x26, 0x91, 0xa6, 0x8c, 0x9b, 0x7e,
	0xa8, 0x90, 0x62, 0x88, 0xfe, 0xee, 0x78, 0xb4, 0xa8, 0x72, 0x0e, 0x0c, 0x21, 0xea, 0x4c, 0x15,
	0xf6, 0x7b, 0xfe, 0xe6, 0x79, 0xf1, 0xfd, 0x6f, 0x9e, 0xef, 0x54, 0x7c, 0x6b, 0xf3, 0xfe, 0xaf,
	0x8a, 0x6f, 0xcd, 0xe7, 0x7f, 0x5a, 0x7c, 0xff, 0xdc, 0x80, 0xb5, 0x6b, 0x5b, 0x6a, 0xee, 0x76,
	0x9a, 0xa6, 0xa6, 0x7b, 0xf4, 0x55, 0xb4, 0xfa, 0x24, 0x1f, 0x41, 0x9b, 0x26, 0x89, 0x59, 0x7b,
	0x2d, 0x2e, 0x90, 0xfb, 0x82, 0xda, 0x72, 0xd8, 0x99, 0x81, 0xc8, 0x0e, 0xb4, 0x13, 0x1a, 0x27,
	0x28, 0xb5, 0x7b, 0x2e, 0xb9, 0x47, 0x0e, 0x24, 0xf4, 0x08, 0xa5, 0xb6, 0xcf, 0xa4, 0x2d, 0x58,
	0xb6, 0x4d, 0xb7, 0x2b, 0x7d, 0xcd, 0xc8, 0x7f, 0x6d, 0xef, 0x42, 0xbb, 0x7e, 0x34, 0x6e, 0x1f,
	0xc6, 0xff, 0xf3, 0xc6, 0xf8, 0x39, 0x74, 0xaf, 0xd7, 0x64, 0xd2, 0x86, 0x66, 0x74, 0x72, 0xdc,
	0x8f, 0x4e, 0x8e, 0xce, 0xba, 0x3f, 0x20, 0x00, 0xcb, 0x67, 0x83, 0xe8, 0xdd, 0xef, 0xff, 0xd0,
	0x6d, 0xf4, 0x3a, 0xd0, 0xae, 0x3f, 0x6d, 0x7a, 0xeb, 0xb0, 0x76, 0xed, 0xdd, 0xd2, 0xeb, 0x42,
	0x67, 0xfe, 0x49, 0xd2, 0x0b, 0x60, 0x6b, 0xf1, 0x2b, 0xa3, 0xb7, 0x05, 0x0f, 0x16, 0x3d, 0x19,
	0x7a, 0x9b, 0xb0, 0xb1, 0xe0, 0x09, 0xd0, 0x9b, 0x40, 0x67, 0xbe, 0x9f, 0x37, 0x9d, 0xfa, 0x98,
	0x72, 0x76, 0x8e, 0x4a, 0xd7, 0x1f, 0xb3, 0xed, 0x0a, 0xb4, 0xfb, 0xf3, 0xe1, 0xce, 0xf5, 0x63,
	0xb8, 0x6b, 0x7b, 0xad, 0x25, 0x9b, 0x38, 0x37, 0x8f, 0x98, 0x8d, 0xf6, 0x0a, 0xe8, 0xf4, 0x95,
	0x66, 0x62, 0xfa, 0x54, 0x20, 0x9f, 0xcc, 0xe9, 0x1e, 0xd6, 0x1f, 0x41, 0xb5, 0x57, 0xb7, 0x93,
	0x93, 0x7d, 0x58, 0x76, 0x17, 0x98, 0xef, 0x78, 0x1f, 0x2d, 0xa2, 0x5b, 0x42, 0xe4, 0x89, 0xbd,
	0xbf, 0x35, 0x60, 0xd9, 0x0d, 0x81, 0x7c, 0x05, 0xcd, 0x31, 0x6a, 0x9a, 0x52, 0x4d, 0xed, 0x04,
	0x5b, 0x07, 0xcf, 0x6b, 0xf9, 0x3d, 0xfd, 0x7f, 0x40, 0x58, 0x5c, 0x64, 0x06, 0x50, 0xa1, 0x61,
	0x9b, 0x8c, 0x77, 0xfa, 0x37, 0xa8, 0x69, 0x34, 0x75, 0x20, 0x87, 0x70, 0xd7, 0x3a, 0xdd, 0xb1,
	0x4e, 0xbf, 0xb8, 0xd5, 0xc9, 0xff, 0x67, 0x21, 0x8c, 0xe8, 0xd5, 0xc9, 0x7b, 0x8d, 0x5c, 0x31,
	0xc1, 0x23, 0x2b, 0xed, 0xfd, 0xb5, 0x01, 0x2b, 0xd3, 0x42, 0xf6, 0x81, 0x37, 0xc3, 0x23, 0x68,
	0x96, 0xa9, 0x72, 0x3b, 0xe3, 0x16, 0xfe, 0x7e, 0x99, 0x2a, 0xbb, 0x29, 0x21, 0x6c, 0x94, 0x0a,
	0x63, 0x2d, 0x4b, 0xa5, 0xaf, 0x84, 0xd4, 0xa3, 0x49, 0xfc, 0xcd, 0x95, 0xf6, 0x7d, 0xc6, 0x7a,
	0xa9, 0xf0, 0x6c, 0x16, 0xf9, 0xf2, 0x4a, 0x93, 0x8f, 0xa1, 0x63, 0xf8, 0x5c, 0xc8, 0x31, 0xcd,
	0x2d, 0xd5, 0x25, 0x5b, 0xbb, 0x54, 0xf8, 0xd6, 0x82, 0x5f, 0x5e, 0xe9, 0xe1, 0xb2, 0xfd, 0xe7,
	0xc7, 0x8b, 0x7f, 0x07, 0x00, 0x00, 0xff, 0xff, 0x50, 0xf3, 0x47, 0xda, 0x05, 0x12, 0x00, 0x00,
}
