// Code generated by protoc-gen-go. DO NOT EDIT.
// source: istioinstaller_types.proto

package v1alpha1

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	v11 "k8s.io/api/autoscaling/v1"
	v1 "k8s.io/api/core/v1"
	v1beta1 "k8s.io/api/policy/v1beta1"
	v12 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
//const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ProxyConfig_InterceptionMode int32

const (
	ProxyConfig_REDIRECT ProxyConfig_InterceptionMode = 0
	ProxyConfig_TPROXY   ProxyConfig_InterceptionMode = 1
)

var ProxyConfig_InterceptionMode_name = map[int32]string{
	0: "REDIRECT",
	1: "TPROXY",
}

var ProxyConfig_InterceptionMode_value = map[string]int32{
	"REDIRECT": 0,
	"TPROXY":   1,
}

func (x ProxyConfig_InterceptionMode) Enum() *ProxyConfig_InterceptionMode {
	p := new(ProxyConfig_InterceptionMode)
	*p = x
	return p
}

func (x ProxyConfig_InterceptionMode) String() string {
	return proto.EnumName(ProxyConfig_InterceptionMode_name, int32(x))
}

func (x *ProxyConfig_InterceptionMode) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(ProxyConfig_InterceptionMode_value, data, "ProxyConfig_InterceptionMode")
	if err != nil {
		return err
	}
	*x = ProxyConfig_InterceptionMode(value)
	return nil
}

func (ProxyConfig_InterceptionMode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_d0a1188b3d395975, []int{5, 0}
}

// InstallerSpec defines the desired state of IstioInstaller.
type InstallerSpec struct {
	// install_package_path is the URL for the install package to install e.g.
	//   http://github.com/istio/istio/releases/install/1.1.2
	//   http://github.com/istio/istio/releases/install/lts
	//   file://tmp/istio-installer/nightly
	// Optional. Uses compiled in install package by default.
	InstallPackagePath *string `protobuf:"bytes,1,opt,name=install_package_path,json=installPackagePath" json:"install_package_path,omitempty"`
	// controller_name binds the CR to the install controller
	// that should listen to it. Used when multiple versions of controllers
	// coexist in a cluster and to prevent old versions of controller from
	// consuming new version of config.
	ControllerName *string `protobuf:"bytes,2,opt,name=controller_name,json=controllerName" json:"controller_name,omitempty"`
	// hub is the root for docker images e.g. docker.io/istio-release.
	Hub *string `protobuf:"bytes,3,opt,name=hub" json:"hub,omitempty"`
	// tag is the version tag for docker images e.g. 1.0.6
	Tag *string `protobuf:"bytes,4,opt,name=tag" json:"tag,omitempty"`
	// default_namespace is the default namespace for components if their
	// namespace is not explicitly set. Required.
	DefaultNamespace *string `protobuf:"bytes,5,opt,name=default_namespace,json=defaultNamespace" json:"default_namespace,omitempty"`
	// remote_cluster_config configures the cluster as a remote cluster.
	RemoteClusterConfig *RemoteClusterConfig `protobuf:"bytes,10,opt,name=remote_cluster_config,json=remoteClusterConfig" json:"remote_cluster_config,omitempty"`
	// Selection and configuration of core Istio features.
	TrafficManagement *TrafficManagementConfig `protobuf:"bytes,20,opt,name=traffic_management,json=trafficManagement" json:"traffic_management,omitempty"`
	Policy            *PolicyConfig            `protobuf:"bytes,21,opt,name=policy" json:"policy,omitempty"`
	Telemetry         *TelemetryConfig         `protobuf:"bytes,22,opt,name=telemetry" json:"telemetry,omitempty"`
	Security          *SecurityConfig          `protobuf:"bytes,23,opt,name=security" json:"security,omitempty"`
	ConfigManagement  *ConfigManagementConfig  `protobuf:"bytes,24,opt,name=config_management,json=configManagement" json:"config_management,omitempty"`
	// Ingress/egress gateway installation and configuration.
	IngressGateway []*IngressGatewayConfig `protobuf:"bytes,30,rep,name=ingress_gateway,json=ingressGateway" json:"ingress_gateway,omitempty"`
	EgressGateway  []*EgressGatewayConfig  `protobuf:"bytes,31,rep,name=egress_gateway,json=egressGateway" json:"egress_gateway,omitempty"`
	// List of external operators that will be installed (but not managed by)
	// IstioInstaller e.g. prometheus, grafana, kiali.
	ExternalOperators    []*OperatorConfig `protobuf:"bytes,50,rep,name=external_operators,json=externalOperators" json:"external_operators,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *InstallerSpec) Reset()         { *m = InstallerSpec{} }
func (m *InstallerSpec) String() string { return proto.CompactTextString(m) }
func (*InstallerSpec) ProtoMessage()    {}
func (*InstallerSpec) Descriptor() ([]byte, []int) {
	return fileDescriptor_d0a1188b3d395975, []int{0}
}

func (m *InstallerSpec) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InstallerSpec.Unmarshal(m, b)
}
func (m *InstallerSpec) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InstallerSpec.Marshal(b, m, deterministic)
}
func (m *InstallerSpec) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InstallerSpec.Merge(m, src)
}
func (m *InstallerSpec) XXX_Size() int {
	return xxx_messageInfo_InstallerSpec.Size(m)
}
func (m *InstallerSpec) XXX_DiscardUnknown() {
	xxx_messageInfo_InstallerSpec.DiscardUnknown(m)
}

var xxx_messageInfo_InstallerSpec proto.InternalMessageInfo

func (m *InstallerSpec) GetInstallPackagePath() string {
	if m != nil && m.InstallPackagePath != nil {
		return *m.InstallPackagePath
	}
	return ""
}

func (m *InstallerSpec) GetControllerName() string {
	if m != nil && m.ControllerName != nil {
		return *m.ControllerName
	}
	return ""
}

func (m *InstallerSpec) GetHub() string {
	if m != nil && m.Hub != nil {
		return *m.Hub
	}
	return ""
}

func (m *InstallerSpec) GetTag() string {
	if m != nil && m.Tag != nil {
		return *m.Tag
	}
	return ""
}

func (m *InstallerSpec) GetDefaultNamespace() string {
	if m != nil && m.DefaultNamespace != nil {
		return *m.DefaultNamespace
	}
	return ""
}

func (m *InstallerSpec) GetRemoteClusterConfig() *RemoteClusterConfig {
	if m != nil {
		return m.RemoteClusterConfig
	}
	return nil
}

func (m *InstallerSpec) GetTrafficManagement() *TrafficManagementConfig {
	if m != nil {
		return m.TrafficManagement
	}
	return nil
}

func (m *InstallerSpec) GetPolicy() *PolicyConfig {
	if m != nil {
		return m.Policy
	}
	return nil
}

func (m *InstallerSpec) GetTelemetry() *TelemetryConfig {
	if m != nil {
		return m.Telemetry
	}
	return nil
}

func (m *InstallerSpec) GetSecurity() *SecurityConfig {
	if m != nil {
		return m.Security
	}
	return nil
}

func (m *InstallerSpec) GetConfigManagement() *ConfigManagementConfig {
	if m != nil {
		return m.ConfigManagement
	}
	return nil
}

func (m *InstallerSpec) GetIngressGateway() []*IngressGatewayConfig {
	if m != nil {
		return m.IngressGateway
	}
	return nil
}

func (m *InstallerSpec) GetEgressGateway() []*EgressGatewayConfig {
	if m != nil {
		return m.EgressGateway
	}
	return nil
}

func (m *InstallerSpec) GetExternalOperators() []*OperatorConfig {
	if m != nil {
		return m.ExternalOperators
	}
	return nil
}

// InstallerStatus defines the observed state of IstioInstaller.
// TODO: this needs more work. What do we want to observe?
type InstallerStatus struct {
	ProxyControl         *string  `protobuf:"bytes,1,opt,name=proxy_control,json=proxyControl" json:"proxy_control,omitempty"`
	SidecarInjector      *string  `protobuf:"bytes,2,opt,name=sidecar_injector,json=sidecarInjector" json:"sidecar_injector,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InstallerStatus) Reset()         { *m = InstallerStatus{} }
func (m *InstallerStatus) String() string { return proto.CompactTextString(m) }
func (*InstallerStatus) ProtoMessage()    {}
func (*InstallerStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_d0a1188b3d395975, []int{1}
}

func (m *InstallerStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InstallerStatus.Unmarshal(m, b)
}
func (m *InstallerStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InstallerStatus.Marshal(b, m, deterministic)
}
func (m *InstallerStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InstallerStatus.Merge(m, src)
}
func (m *InstallerStatus) XXX_Size() int {
	return xxx_messageInfo_InstallerStatus.Size(m)
}
func (m *InstallerStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_InstallerStatus.DiscardUnknown(m)
}

var xxx_messageInfo_InstallerStatus proto.InternalMessageInfo

func (m *InstallerStatus) GetProxyControl() string {
	if m != nil && m.ProxyControl != nil {
		return *m.ProxyControl
	}
	return ""
}

func (m *InstallerStatus) GetSidecarInjector() string {
	if m != nil && m.SidecarInjector != nil {
		return *m.SidecarInjector
	}
	return ""
}

// RemoteClusterConfig defines configuration options for remote clusters.
type RemoteClusterConfig struct {
	// Enabled selects whether the cluster is configured as remote.
	Enabled *bool `protobuf:"varint,1,opt,name=enabled" json:"enabled,omitempty"`
	// Namespace that all components for this feature are installed into.
	Namespace *string `protobuf:"bytes,2,opt,name=namespace" json:"namespace,omitempty"`
	// resource_override is a kustomize style overlay to kubernetes resources
	// in the manifests rendered from the chart templates using included
	// values.yaml with ValuesOverride above.
	ResourceOverride     []*Object `protobuf:"bytes,3,rep,name=resource_override,json=resourceOverride" json:"resource_override,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *RemoteClusterConfig) Reset()         { *m = RemoteClusterConfig{} }
func (m *RemoteClusterConfig) String() string { return proto.CompactTextString(m) }
func (*RemoteClusterConfig) ProtoMessage()    {}
func (*RemoteClusterConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_d0a1188b3d395975, []int{2}
}

func (m *RemoteClusterConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoteClusterConfig.Unmarshal(m, b)
}
func (m *RemoteClusterConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoteClusterConfig.Marshal(b, m, deterministic)
}
func (m *RemoteClusterConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoteClusterConfig.Merge(m, src)
}
func (m *RemoteClusterConfig) XXX_Size() int {
	return xxx_messageInfo_RemoteClusterConfig.Size(m)
}
func (m *RemoteClusterConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoteClusterConfig.DiscardUnknown(m)
}

var xxx_messageInfo_RemoteClusterConfig proto.InternalMessageInfo

func (m *RemoteClusterConfig) GetEnabled() bool {
	if m != nil && m.Enabled != nil {
		return *m.Enabled
	}
	return false
}

func (m *RemoteClusterConfig) GetNamespace() string {
	if m != nil && m.Namespace != nil {
		return *m.Namespace
	}
	return ""
}

func (m *RemoteClusterConfig) GetResourceOverride() []*Object {
	if m != nil {
		return m.ResourceOverride
	}
	return nil
}

// TrafficManagementConfig defines configuration options for proxy control and injection.
type TrafficManagementConfig struct {
	// Selects whether traffic management is installed.
	Enabled *bool `protobuf:"varint,1,opt,name=enabled" json:"enabled,omitempty"`
	// Namespace that all components for this feature are installed into.
	Namespace *string `protobuf:"bytes,2,opt,name=namespace" json:"namespace,omitempty"`
	// When set to true, auto injection is controlled by namespace label and pod annotation.
	// When set to false, auto injection is completely disabled.
	AutoInjection *bool `protobuf:"varint,3,opt,name=auto_injection,json=autoInjection" json:"auto_injection,omitempty"`
	// Component specific config.
	PilotConfig          *PilotConfig `protobuf:"bytes,4,opt,name=pilot_config,json=pilotConfig" json:"pilot_config,omitempty"`
	ProxyConfig          *ProxyConfig `protobuf:"bytes,5,opt,name=proxy_config,json=proxyConfig" json:"proxy_config,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *TrafficManagementConfig) Reset()         { *m = TrafficManagementConfig{} }
func (m *TrafficManagementConfig) String() string { return proto.CompactTextString(m) }
func (*TrafficManagementConfig) ProtoMessage()    {}
func (*TrafficManagementConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_d0a1188b3d395975, []int{3}
}

func (m *TrafficManagementConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TrafficManagementConfig.Unmarshal(m, b)
}
func (m *TrafficManagementConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TrafficManagementConfig.Marshal(b, m, deterministic)
}
func (m *TrafficManagementConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TrafficManagementConfig.Merge(m, src)
}
func (m *TrafficManagementConfig) XXX_Size() int {
	return xxx_messageInfo_TrafficManagementConfig.Size(m)
}
func (m *TrafficManagementConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_TrafficManagementConfig.DiscardUnknown(m)
}

var xxx_messageInfo_TrafficManagementConfig proto.InternalMessageInfo

func (m *TrafficManagementConfig) GetEnabled() bool {
	if m != nil && m.Enabled != nil {
		return *m.Enabled
	}
	return false
}

func (m *TrafficManagementConfig) GetNamespace() string {
	if m != nil && m.Namespace != nil {
		return *m.Namespace
	}
	return ""
}

func (m *TrafficManagementConfig) GetAutoInjection() bool {
	if m != nil && m.AutoInjection != nil {
		return *m.AutoInjection
	}
	return false
}

func (m *TrafficManagementConfig) GetPilotConfig() *PilotConfig {
	if m != nil {
		return m.PilotConfig
	}
	return nil
}

func (m *TrafficManagementConfig) GetProxyConfig() *ProxyConfig {
	if m != nil {
		return m.ProxyConfig
	}
	return nil
}

// PilotConfig defines the configuration options for pilot.
type PilotConfig struct {
	// Enables debug in pilot.
	Debug *bool `protobuf:"varint,1,opt,name=debug" json:"debug,omitempty"`
	// Enables sidecar in the pilot pod.
	Sidecar *bool `protobuf:"varint,2,opt,name=sidecar" json:"sidecar,omitempty"`
	// Trace sampling percentage.
	TraceSampling *float32 `protobuf:"fixed32,3,opt,name=trace_sampling,json=traceSampling" json:"trace_sampling,omitempty"`
	// Passthrough to corresponding k8s settings.
	Resources           *v1.ResourceRequirements         `protobuf:"bytes,50,opt,name=resources" json:"resources,omitempty"`
	HpaSpec             *v11.HorizontalPodAutoscalerSpec `protobuf:"bytes,51,opt,name=hpa_spec,json=hpaSpec" json:"hpa_spec,omitempty"`
	PodDisruptionBudget *v1beta1.PodDisruptionBudget     `protobuf:"bytes,52,opt,name=pod_disruption_budget,json=podDisruptionBudget" json:"pod_disruption_budget,omitempty"`
	NodeSelector        *v1.NodeSelector                 `protobuf:"bytes,53,opt,name=nodeSelector" json:"nodeSelector,omitempty"`
	// Additional arguments passed to pilot discovery.
	AdditionalArgs map[string]string `protobuf:"bytes,60,rep,name=additional_args,json=additionalArgs" json:"additional_args,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Additional environment variables for the discovery container.
	Env map[string]string `protobuf:"bytes,70,rep,name=env" json:"env,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Kustomize style overrides for k8s resources in rendered manifests.
	ResourceOverride     []*Object `protobuf:"bytes,100,rep,name=resource_override,json=resourceOverride" json:"resource_override,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *PilotConfig) Reset()         { *m = PilotConfig{} }
func (m *PilotConfig) String() string { return proto.CompactTextString(m) }
func (*PilotConfig) ProtoMessage()    {}
func (*PilotConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_d0a1188b3d395975, []int{4}
}

func (m *PilotConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PilotConfig.Unmarshal(m, b)
}
func (m *PilotConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PilotConfig.Marshal(b, m, deterministic)
}
func (m *PilotConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PilotConfig.Merge(m, src)
}
func (m *PilotConfig) XXX_Size() int {
	return xxx_messageInfo_PilotConfig.Size(m)
}
func (m *PilotConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_PilotConfig.DiscardUnknown(m)
}

var xxx_messageInfo_PilotConfig proto.InternalMessageInfo

func (m *PilotConfig) GetDebug() bool {
	if m != nil && m.Debug != nil {
		return *m.Debug
	}
	return false
}

func (m *PilotConfig) GetSidecar() bool {
	if m != nil && m.Sidecar != nil {
		return *m.Sidecar
	}
	return false
}

func (m *PilotConfig) GetTraceSampling() float32 {
	if m != nil && m.TraceSampling != nil {
		return *m.TraceSampling
	}
	return 0
}

func (m *PilotConfig) GetResources() *v1.ResourceRequirements {
	if m != nil {
		return m.Resources
	}
	return nil
}

func (m *PilotConfig) GetHpaSpec() *v11.HorizontalPodAutoscalerSpec {
	if m != nil {
		return m.HpaSpec
	}
	return nil
}

func (m *PilotConfig) GetPodDisruptionBudget() *v1beta1.PodDisruptionBudget {
	if m != nil {
		return m.PodDisruptionBudget
	}
	return nil
}

func (m *PilotConfig) GetNodeSelector() *v1.NodeSelector {
	if m != nil {
		return m.NodeSelector
	}
	return nil
}

func (m *PilotConfig) GetAdditionalArgs() map[string]string {
	if m != nil {
		return m.AdditionalArgs
	}
	return nil
}

func (m *PilotConfig) GetEnv() map[string]string {
	if m != nil {
		return m.Env
	}
	return nil
}

func (m *PilotConfig) GetResourceOverride() []*Object {
	if m != nil {
		return m.ResourceOverride
	}
	return nil
}

// ProxyConfig defines the configuration options for the injected Envoy proxy.
type ProxyConfig struct {
	// Enables debug in the proxy.
	Debug *bool `protobuf:"varint,1,opt,name=debug" json:"debug,omitempty"`
	// TBD: is privileged ever set in isolation?
	Privileged *bool `protobuf:"varint,2,opt,name=privileged" json:"privileged,omitempty"`
	// Enables coredump in proxy container.
	EnableCoredump   *bool                         `protobuf:"varint,3,opt,name=enable_coredump,json=enableCoredump" json:"enable_coredump,omitempty"`
	InterceptionMode *ProxyConfig_InterceptionMode `protobuf:"varint,4,opt,name=interception_mode,json=interceptionMode,enum=v1alpha1.ProxyConfig_InterceptionMode" json:"interception_mode,omitempty"`
	// Below settings would otherwise be implemented as a k8s overlay but because the proxy resources are defined
	// as a ConfigMap containing a second template, it's probably too difficult to override fields in the k8s
	// ConfigMap.
	StatusPort      *uint32 `protobuf:"varint,5,opt,name=status_port,json=statusPort" json:"status_port,omitempty"`
	ImagePullPolicy *string `protobuf:"bytes,6,opt,name=image_pull_policy,json=imagePullPolicy" json:"image_pull_policy,omitempty"`
	ProxyInitImage  *string `protobuf:"bytes,7,opt,name=proxy_init_image,json=proxyInitImage" json:"proxy_init_image,omitempty"`
	// Address and port filtering.
	IncludeIpRanges     *string `protobuf:"bytes,8,opt,name=include_ip_ranges,json=includeIpRanges" json:"include_ip_ranges,omitempty"`
	ExcludeIpRanges     *string `protobuf:"bytes,9,opt,name=exclude_ip_ranges,json=excludeIpRanges" json:"exclude_ip_ranges,omitempty"`
	IncludeInboundPorts *string `protobuf:"bytes,10,opt,name=include_inbound_ports,json=includeInboundPorts" json:"include_inbound_ports,omitempty"`
	ExcludeInboundPorts *string `protobuf:"bytes,11,opt,name=exclude_inbound_ports,json=excludeInboundPorts" json:"exclude_inbound_ports,omitempty"`
	// Envoy specific timer settings.
	ConnectTimeout         *string `protobuf:"bytes,12,opt,name=connect_timeout,json=connectTimeout" json:"connect_timeout,omitempty"`
	DrainDuration          *string `protobuf:"bytes,13,opt,name=drain_duration,json=drainDuration" json:"drain_duration,omitempty"`
	ParentShutdownDuration *string `protobuf:"bytes,14,opt,name=parent_shutdown_duration,json=parentShutdownDuration" json:"parent_shutdown_duration,omitempty"`
	Concurrency            *uint32 `protobuf:"varint,15,opt,name=concurrency" json:"concurrency,omitempty"`
	ClusterDomain          *string `protobuf:"bytes,16,opt,name=cluster_domain,json=clusterDomain" json:"cluster_domain,omitempty"`
	PodDnsSearchNamespaces *string `protobuf:"bytes,17,opt,name=pod_dns_search_namespaces,json=podDnsSearchNamespaces" json:"pod_dns_search_namespaces,omitempty"`
	// Tracer options
	Lightstep *ProxyConfig_LightstepConfig `protobuf:"bytes,30,opt,name=lightstep" json:"lightstep,omitempty"`
	Zipkin    *ProxyConfig_ZipkinConfig    `protobuf:"bytes,31,opt,name=zipkin" json:"zipkin,omitempty"`
	// SDS settings
	Sds *SdsConfig `protobuf:"bytes,40,opt,name=sds" json:"sds,omitempty"`
	// Passthrough to k8s resources.
	ReadinessProbe *v1.Probe                `protobuf:"bytes,50,opt,name=readiness_probe,json=readinessProbe" json:"readiness_probe,omitempty"`
	Resources      *v1.ResourceRequirements `protobuf:"bytes,51,opt,name=resources" json:"resources,omitempty"`
	// Additional arguments passed to Envoy.
	AdditionalArgs map[string]string `protobuf:"bytes,60,rep,name=additional_args,json=additionalArgs" json:"additional_args,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Additional environment variables for the container.
	Env map[string]string `protobuf:"bytes,70,rep,name=env" json:"env,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Kustomize style overrides for k8s resources in rendered manifests.
	ResourceOverride     []*Object `protobuf:"bytes,100,rep,name=resource_override,json=resourceOverride" json:"resource_override,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *ProxyConfig) Reset()         { *m = ProxyConfig{} }
func (m *ProxyConfig) String() string { return proto.CompactTextString(m) }
func (*ProxyConfig) ProtoMessage()    {}
func (*ProxyConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_d0a1188b3d395975, []int{5}
}

func (m *ProxyConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProxyConfig.Unmarshal(m, b)
}
func (m *ProxyConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProxyConfig.Marshal(b, m, deterministic)
}
func (m *ProxyConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProxyConfig.Merge(m, src)
}
func (m *ProxyConfig) XXX_Size() int {
	return xxx_messageInfo_ProxyConfig.Size(m)
}
func (m *ProxyConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_ProxyConfig.DiscardUnknown(m)
}

var xxx_messageInfo_ProxyConfig proto.InternalMessageInfo

func (m *ProxyConfig) GetDebug() bool {
	if m != nil && m.Debug != nil {
		return *m.Debug
	}
	return false
}

func (m *ProxyConfig) GetPrivileged() bool {
	if m != nil && m.Privileged != nil {
		return *m.Privileged
	}
	return false
}

func (m *ProxyConfig) GetEnableCoredump() bool {
	if m != nil && m.EnableCoredump != nil {
		return *m.EnableCoredump
	}
	return false
}

func (m *ProxyConfig) GetInterceptionMode() ProxyConfig_InterceptionMode {
	if m != nil && m.InterceptionMode != nil {
		return *m.InterceptionMode
	}
	return ProxyConfig_REDIRECT
}

func (m *ProxyConfig) GetStatusPort() uint32 {
	if m != nil && m.StatusPort != nil {
		return *m.StatusPort
	}
	return 0
}

func (m *ProxyConfig) GetImagePullPolicy() string {
	if m != nil && m.ImagePullPolicy != nil {
		return *m.ImagePullPolicy
	}
	return ""
}

func (m *ProxyConfig) GetProxyInitImage() string {
	if m != nil && m.ProxyInitImage != nil {
		return *m.ProxyInitImage
	}
	return ""
}

func (m *ProxyConfig) GetIncludeIpRanges() string {
	if m != nil && m.IncludeIpRanges != nil {
		return *m.IncludeIpRanges
	}
	return ""
}

func (m *ProxyConfig) GetExcludeIpRanges() string {
	if m != nil && m.ExcludeIpRanges != nil {
		return *m.ExcludeIpRanges
	}
	return ""
}

func (m *ProxyConfig) GetIncludeInboundPorts() string {
	if m != nil && m.IncludeInboundPorts != nil {
		return *m.IncludeInboundPorts
	}
	return ""
}

func (m *ProxyConfig) GetExcludeInboundPorts() string {
	if m != nil && m.ExcludeInboundPorts != nil {
		return *m.ExcludeInboundPorts
	}
	return ""
}

func (m *ProxyConfig) GetConnectTimeout() string {
	if m != nil && m.ConnectTimeout != nil {
		return *m.ConnectTimeout
	}
	return ""
}

func (m *ProxyConfig) GetDrainDuration() string {
	if m != nil && m.DrainDuration != nil {
		return *m.DrainDuration
	}
	return ""
}

func (m *ProxyConfig) GetParentShutdownDuration() string {
	if m != nil && m.ParentShutdownDuration != nil {
		return *m.ParentShutdownDuration
	}
	return ""
}

func (m *ProxyConfig) GetConcurrency() uint32 {
	if m != nil && m.Concurrency != nil {
		return *m.Concurrency
	}
	return 0
}

func (m *ProxyConfig) GetClusterDomain() string {
	if m != nil && m.ClusterDomain != nil {
		return *m.ClusterDomain
	}
	return ""
}

func (m *ProxyConfig) GetPodDnsSearchNamespaces() string {
	if m != nil && m.PodDnsSearchNamespaces != nil {
		return *m.PodDnsSearchNamespaces
	}
	return ""
}

func (m *ProxyConfig) GetLightstep() *ProxyConfig_LightstepConfig {
	if m != nil {
		return m.Lightstep
	}
	return nil
}

func (m *ProxyConfig) GetZipkin() *ProxyConfig_ZipkinConfig {
	if m != nil {
		return m.Zipkin
	}
	return nil
}

func (m *ProxyConfig) GetSds() *SdsConfig {
	if m != nil {
		return m.Sds
	}
	return nil
}

func (m *ProxyConfig) GetReadinessProbe() *v1.Probe {
	if m != nil {
		return m.ReadinessProbe
	}
	return nil
}

func (m *ProxyConfig) GetResources() *v1.ResourceRequirements {
	if m != nil {
		return m.Resources
	}
	return nil
}

func (m *ProxyConfig) GetAdditionalArgs() map[string]string {
	if m != nil {
		return m.AdditionalArgs
	}
	return nil
}

func (m *ProxyConfig) GetEnv() map[string]string {
	if m != nil {
		return m.Env
	}
	return nil
}

func (m *ProxyConfig) GetResourceOverride() []*Object {
	if m != nil {
		return m.ResourceOverride
	}
	return nil
}

// Tracer config options.
type ProxyConfig_LightstepConfig struct {
	Address              *string  `protobuf:"bytes,1,opt,name=address" json:"address,omitempty"`
	AccessToken          *string  `protobuf:"bytes,2,opt,name=access_token,json=accessToken" json:"access_token,omitempty"`
	CaCertPath           *string  `protobuf:"bytes,3,opt,name=ca_cert_path,json=caCertPath" json:"ca_cert_path,omitempty"`
	Secure               *bool    `protobuf:"varint,4,opt,name=secure" json:"secure,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProxyConfig_LightstepConfig) Reset()         { *m = ProxyConfig_LightstepConfig{} }
func (m *ProxyConfig_LightstepConfig) String() string { return proto.CompactTextString(m) }
func (*ProxyConfig_LightstepConfig) ProtoMessage()    {}
func (*ProxyConfig_LightstepConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_d0a1188b3d395975, []int{5, 0}
}

func (m *ProxyConfig_LightstepConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProxyConfig_LightstepConfig.Unmarshal(m, b)
}
func (m *ProxyConfig_LightstepConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProxyConfig_LightstepConfig.Marshal(b, m, deterministic)
}
func (m *ProxyConfig_LightstepConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProxyConfig_LightstepConfig.Merge(m, src)
}
func (m *ProxyConfig_LightstepConfig) XXX_Size() int {
	return xxx_messageInfo_ProxyConfig_LightstepConfig.Size(m)
}
func (m *ProxyConfig_LightstepConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_ProxyConfig_LightstepConfig.DiscardUnknown(m)
}

var xxx_messageInfo_ProxyConfig_LightstepConfig proto.InternalMessageInfo

func (m *ProxyConfig_LightstepConfig) GetAddress() string {
	if m != nil && m.Address != nil {
		return *m.Address
	}
	return ""
}

func (m *ProxyConfig_LightstepConfig) GetAccessToken() string {
	if m != nil && m.AccessToken != nil {
		return *m.AccessToken
	}
	return ""
}

func (m *ProxyConfig_LightstepConfig) GetCaCertPath() string {
	if m != nil && m.CaCertPath != nil {
		return *m.CaCertPath
	}
	return ""
}

func (m *ProxyConfig_LightstepConfig) GetSecure() bool {
	if m != nil && m.Secure != nil {
		return *m.Secure
	}
	return false
}

type ProxyConfig_ZipkinConfig struct {
	Address              *string  `protobuf:"bytes,1,opt,name=address" json:"address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProxyConfig_ZipkinConfig) Reset()         { *m = ProxyConfig_ZipkinConfig{} }
func (m *ProxyConfig_ZipkinConfig) String() string { return proto.CompactTextString(m) }
func (*ProxyConfig_ZipkinConfig) ProtoMessage()    {}
func (*ProxyConfig_ZipkinConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_d0a1188b3d395975, []int{5, 1}
}

func (m *ProxyConfig_ZipkinConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProxyConfig_ZipkinConfig.Unmarshal(m, b)
}
func (m *ProxyConfig_ZipkinConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProxyConfig_ZipkinConfig.Marshal(b, m, deterministic)
}
func (m *ProxyConfig_ZipkinConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProxyConfig_ZipkinConfig.Merge(m, src)
}
func (m *ProxyConfig_ZipkinConfig) XXX_Size() int {
	return xxx_messageInfo_ProxyConfig_ZipkinConfig.Size(m)
}
func (m *ProxyConfig_ZipkinConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_ProxyConfig_ZipkinConfig.DiscardUnknown(m)
}

var xxx_messageInfo_ProxyConfig_ZipkinConfig proto.InternalMessageInfo

func (m *ProxyConfig_ZipkinConfig) GetAddress() string {
	if m != nil && m.Address != nil {
		return *m.Address
	}
	return ""
}

type PolicyConfig struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PolicyConfig) Reset()         { *m = PolicyConfig{} }
func (m *PolicyConfig) String() string { return proto.CompactTextString(m) }
func (*PolicyConfig) ProtoMessage()    {}
func (*PolicyConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_d0a1188b3d395975, []int{6}
}

func (m *PolicyConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PolicyConfig.Unmarshal(m, b)
}
func (m *PolicyConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PolicyConfig.Marshal(b, m, deterministic)
}
func (m *PolicyConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PolicyConfig.Merge(m, src)
}
func (m *PolicyConfig) XXX_Size() int {
	return xxx_messageInfo_PolicyConfig.Size(m)
}
func (m *PolicyConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_PolicyConfig.DiscardUnknown(m)
}

var xxx_messageInfo_PolicyConfig proto.InternalMessageInfo

type TelemetryConfig struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TelemetryConfig) Reset()         { *m = TelemetryConfig{} }
func (m *TelemetryConfig) String() string { return proto.CompactTextString(m) }
func (*TelemetryConfig) ProtoMessage()    {}
func (*TelemetryConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_d0a1188b3d395975, []int{7}
}

func (m *TelemetryConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TelemetryConfig.Unmarshal(m, b)
}
func (m *TelemetryConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TelemetryConfig.Marshal(b, m, deterministic)
}
func (m *TelemetryConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TelemetryConfig.Merge(m, src)
}
func (m *TelemetryConfig) XXX_Size() int {
	return xxx_messageInfo_TelemetryConfig.Size(m)
}
func (m *TelemetryConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_TelemetryConfig.DiscardUnknown(m)
}

var xxx_messageInfo_TelemetryConfig proto.InternalMessageInfo

type SecurityConfig struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SecurityConfig) Reset()         { *m = SecurityConfig{} }
func (m *SecurityConfig) String() string { return proto.CompactTextString(m) }
func (*SecurityConfig) ProtoMessage()    {}
func (*SecurityConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_d0a1188b3d395975, []int{8}
}

func (m *SecurityConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SecurityConfig.Unmarshal(m, b)
}
func (m *SecurityConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SecurityConfig.Marshal(b, m, deterministic)
}
func (m *SecurityConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SecurityConfig.Merge(m, src)
}
func (m *SecurityConfig) XXX_Size() int {
	return xxx_messageInfo_SecurityConfig.Size(m)
}
func (m *SecurityConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_SecurityConfig.DiscardUnknown(m)
}

var xxx_messageInfo_SecurityConfig proto.InternalMessageInfo

type ConfigManagementConfig struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConfigManagementConfig) Reset()         { *m = ConfigManagementConfig{} }
func (m *ConfigManagementConfig) String() string { return proto.CompactTextString(m) }
func (*ConfigManagementConfig) ProtoMessage()    {}
func (*ConfigManagementConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_d0a1188b3d395975, []int{9}
}

func (m *ConfigManagementConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConfigManagementConfig.Unmarshal(m, b)
}
func (m *ConfigManagementConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConfigManagementConfig.Marshal(b, m, deterministic)
}
func (m *ConfigManagementConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfigManagementConfig.Merge(m, src)
}
func (m *ConfigManagementConfig) XXX_Size() int {
	return xxx_messageInfo_ConfigManagementConfig.Size(m)
}
func (m *ConfigManagementConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfigManagementConfig.DiscardUnknown(m)
}

var xxx_messageInfo_ConfigManagementConfig proto.InternalMessageInfo

type IngressGatewayConfig struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IngressGatewayConfig) Reset()         { *m = IngressGatewayConfig{} }
func (m *IngressGatewayConfig) String() string { return proto.CompactTextString(m) }
func (*IngressGatewayConfig) ProtoMessage()    {}
func (*IngressGatewayConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_d0a1188b3d395975, []int{10}
}

func (m *IngressGatewayConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IngressGatewayConfig.Unmarshal(m, b)
}
func (m *IngressGatewayConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IngressGatewayConfig.Marshal(b, m, deterministic)
}
func (m *IngressGatewayConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IngressGatewayConfig.Merge(m, src)
}
func (m *IngressGatewayConfig) XXX_Size() int {
	return xxx_messageInfo_IngressGatewayConfig.Size(m)
}
func (m *IngressGatewayConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_IngressGatewayConfig.DiscardUnknown(m)
}

var xxx_messageInfo_IngressGatewayConfig proto.InternalMessageInfo

type EgressGatewayConfig struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EgressGatewayConfig) Reset()         { *m = EgressGatewayConfig{} }
func (m *EgressGatewayConfig) String() string { return proto.CompactTextString(m) }
func (*EgressGatewayConfig) ProtoMessage()    {}
func (*EgressGatewayConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_d0a1188b3d395975, []int{11}
}

func (m *EgressGatewayConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EgressGatewayConfig.Unmarshal(m, b)
}
func (m *EgressGatewayConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EgressGatewayConfig.Marshal(b, m, deterministic)
}
func (m *EgressGatewayConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EgressGatewayConfig.Merge(m, src)
}
func (m *EgressGatewayConfig) XXX_Size() int {
	return xxx_messageInfo_EgressGatewayConfig.Size(m)
}
func (m *EgressGatewayConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_EgressGatewayConfig.DiscardUnknown(m)
}

var xxx_messageInfo_EgressGatewayConfig proto.InternalMessageInfo

// OperatorConfig defines a config used to install an external operator.
type OperatorConfig struct {
	// manifest_path is the URL for the operator install manifest.
	ManifestPath *string `protobuf:"bytes,1,opt,name=manifest_path,json=manifestPath" json:"manifest_path,omitempty"`
	// namespace is the namespace the operator manifest and CR are installed into.
	Namespace *string `protobuf:"bytes,2,opt,name=namespace" json:"namespace,omitempty"`
	// spec is the initial CR for the operator.
	Spec                 *Object  `protobuf:"bytes,3,opt,name=spec" json:"spec,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OperatorConfig) Reset()         { *m = OperatorConfig{} }
func (m *OperatorConfig) String() string { return proto.CompactTextString(m) }
func (*OperatorConfig) ProtoMessage()    {}
func (*OperatorConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_d0a1188b3d395975, []int{12}
}

func (m *OperatorConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OperatorConfig.Unmarshal(m, b)
}
func (m *OperatorConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OperatorConfig.Marshal(b, m, deterministic)
}
func (m *OperatorConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OperatorConfig.Merge(m, src)
}
func (m *OperatorConfig) XXX_Size() int {
	return xxx_messageInfo_OperatorConfig.Size(m)
}
func (m *OperatorConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_OperatorConfig.DiscardUnknown(m)
}

var xxx_messageInfo_OperatorConfig proto.InternalMessageInfo

func (m *OperatorConfig) GetManifestPath() string {
	if m != nil && m.ManifestPath != nil {
		return *m.ManifestPath
	}
	return ""
}

func (m *OperatorConfig) GetNamespace() string {
	if m != nil && m.Namespace != nil {
		return *m.Namespace
	}
	return ""
}

func (m *OperatorConfig) GetSpec() *Object {
	if m != nil {
		return m.Spec
	}
	return nil
}

type IstioInstaller struct {
	Spec                 *InstallerSpec   `protobuf:"bytes,3,opt,name=spec" json:"spec,omitempty"`
	Status               *InstallerStatus `protobuf:"bytes,4,opt,name=status" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *IstioInstaller) Reset()         { *m = IstioInstaller{} }
func (m *IstioInstaller) String() string { return proto.CompactTextString(m) }
func (*IstioInstaller) ProtoMessage()    {}
func (*IstioInstaller) Descriptor() ([]byte, []int) {
	return fileDescriptor_d0a1188b3d395975, []int{13}
}

func (m *IstioInstaller) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IstioInstaller.Unmarshal(m, b)
}
func (m *IstioInstaller) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IstioInstaller.Marshal(b, m, deterministic)
}
func (m *IstioInstaller) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IstioInstaller.Merge(m, src)
}
func (m *IstioInstaller) XXX_Size() int {
	return xxx_messageInfo_IstioInstaller.Size(m)
}
func (m *IstioInstaller) XXX_DiscardUnknown() {
	xxx_messageInfo_IstioInstaller.DiscardUnknown(m)
}

var xxx_messageInfo_IstioInstaller proto.InternalMessageInfo

func (m *IstioInstaller) GetSpec() *InstallerSpec {
	if m != nil {
		return m.Spec
	}
	return nil
}

func (m *IstioInstaller) GetStatus() *InstallerStatus {
	if m != nil {
		return m.Status
	}
	return nil
}

type Object struct {
	Metadata             *v12.ObjectMeta       `protobuf:"bytes,1,opt,name=metadata" json:"metadata,omitempty"`
	Data                 *runtime.RawExtension `protobuf:"bytes,2,opt,name=data" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *Object) Reset()         { *m = Object{} }
func (m *Object) String() string { return proto.CompactTextString(m) }
func (*Object) ProtoMessage()    {}
func (*Object) Descriptor() ([]byte, []int) {
	return fileDescriptor_d0a1188b3d395975, []int{14}
}

func (m *Object) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Object.Unmarshal(m, b)
}
func (m *Object) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Object.Marshal(b, m, deterministic)
}
func (m *Object) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Object.Merge(m, src)
}
func (m *Object) XXX_Size() int {
	return xxx_messageInfo_Object.Size(m)
}
func (m *Object) XXX_DiscardUnknown() {
	xxx_messageInfo_Object.DiscardUnknown(m)
}

var xxx_messageInfo_Object proto.InternalMessageInfo

func (m *Object) GetMetadata() *v12.ObjectMeta {
	if m != nil {
		return m.Metadata
	}
	return nil
}

func (m *Object) GetData() *runtime.RawExtension {
	if m != nil {
		return m.Data
	}
	return nil
}

// FIXME: this should be moved out
type SdsConfig struct {
	Enabled              *bool    `protobuf:"varint,1,opt,name=enabled" json:"enabled,omitempty"`
	UdsPath              *string  `protobuf:"bytes,2,opt,name=uds_path,json=udsPath" json:"uds_path,omitempty"`
	UseTrustworthyJwt    *bool    `protobuf:"varint,3,opt,name=use_trustworthy_jwt,json=useTrustworthyJwt" json:"use_trustworthy_jwt,omitempty"`
	UseNormalJwt         *bool    `protobuf:"varint,4,opt,name=use_normal_jwt,json=useNormalJwt" json:"use_normal_jwt,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SdsConfig) Reset()         { *m = SdsConfig{} }
func (m *SdsConfig) String() string { return proto.CompactTextString(m) }
func (*SdsConfig) ProtoMessage()    {}
func (*SdsConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_d0a1188b3d395975, []int{15}
}

func (m *SdsConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SdsConfig.Unmarshal(m, b)
}
func (m *SdsConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SdsConfig.Marshal(b, m, deterministic)
}
func (m *SdsConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SdsConfig.Merge(m, src)
}
func (m *SdsConfig) XXX_Size() int {
	return xxx_messageInfo_SdsConfig.Size(m)
}
func (m *SdsConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_SdsConfig.DiscardUnknown(m)
}

var xxx_messageInfo_SdsConfig proto.InternalMessageInfo

func (m *SdsConfig) GetEnabled() bool {
	if m != nil && m.Enabled != nil {
		return *m.Enabled
	}
	return false
}

func (m *SdsConfig) GetUdsPath() string {
	if m != nil && m.UdsPath != nil {
		return *m.UdsPath
	}
	return ""
}

func (m *SdsConfig) GetUseTrustworthyJwt() bool {
	if m != nil && m.UseTrustworthyJwt != nil {
		return *m.UseTrustworthyJwt
	}
	return false
}

func (m *SdsConfig) GetUseNormalJwt() bool {
	if m != nil && m.UseNormalJwt != nil {
		return *m.UseNormalJwt
	}
	return false
}

func init() {
	proto.RegisterEnum("v1alpha1.ProxyConfig_InterceptionMode", ProxyConfig_InterceptionMode_name, ProxyConfig_InterceptionMode_value)
	proto.RegisterType((*InstallerSpec)(nil), "v1alpha1.InstallerSpec")
	proto.RegisterType((*InstallerStatus)(nil), "v1alpha1.InstallerStatus")
	proto.RegisterType((*RemoteClusterConfig)(nil), "v1alpha1.RemoteClusterConfig")
	proto.RegisterType((*TrafficManagementConfig)(nil), "v1alpha1.TrafficManagementConfig")
	proto.RegisterType((*PilotConfig)(nil), "v1alpha1.PilotConfig")
	proto.RegisterMapType((map[string]string)(nil), "v1alpha1.PilotConfig.AdditionalArgsEntry")
	proto.RegisterMapType((map[string]string)(nil), "v1alpha1.PilotConfig.EnvEntry")
	proto.RegisterType((*ProxyConfig)(nil), "v1alpha1.ProxyConfig")
	proto.RegisterMapType((map[string]string)(nil), "v1alpha1.ProxyConfig.AdditionalArgsEntry")
	proto.RegisterMapType((map[string]string)(nil), "v1alpha1.ProxyConfig.EnvEntry")
	proto.RegisterType((*ProxyConfig_LightstepConfig)(nil), "v1alpha1.ProxyConfig.LightstepConfig")
	proto.RegisterType((*ProxyConfig_ZipkinConfig)(nil), "v1alpha1.ProxyConfig.ZipkinConfig")
	proto.RegisterType((*PolicyConfig)(nil), "v1alpha1.PolicyConfig")
	proto.RegisterType((*TelemetryConfig)(nil), "v1alpha1.TelemetryConfig")
	proto.RegisterType((*SecurityConfig)(nil), "v1alpha1.SecurityConfig")
	proto.RegisterType((*ConfigManagementConfig)(nil), "v1alpha1.ConfigManagementConfig")
	proto.RegisterType((*IngressGatewayConfig)(nil), "v1alpha1.IngressGatewayConfig")
	proto.RegisterType((*EgressGatewayConfig)(nil), "v1alpha1.EgressGatewayConfig")
	proto.RegisterType((*OperatorConfig)(nil), "v1alpha1.OperatorConfig")
	proto.RegisterType((*IstioInstaller)(nil), "v1alpha1.IstioInstaller")
	proto.RegisterType((*Object)(nil), "v1alpha1.Object")
	proto.RegisterType((*SdsConfig)(nil), "v1alpha1.SdsConfig")
}

func init() { proto.RegisterFile("istioinstaller_types.proto", fileDescriptor_d0a1188b3d395975) }

var fileDescriptor_d0a1188b3d395975 = []byte{
	// 1786 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xc4, 0x58, 0xdd, 0x72, 0x1b, 0x49,
	0x15, 0x46, 0x71, 0xe2, 0xc8, 0x47, 0xb2, 0x2c, 0xb7, 0x63, 0xef, 0xd8, 0x05, 0x89, 0x57, 0x6c,
	0xc0, 0x61, 0x61, 0x1c, 0x7b, 0xc3, 0x12, 0xb6, 0xe0, 0xc2, 0x6b, 0x7b, 0x83, 0xb6, 0x36, 0x89,
	0x76, 0xec, 0x0b, 0xe0, 0x66, 0xaa, 0x3d, 0x73, 0x3c, 0xea, 0xf5, 0xa8, 0x7b, 0xe8, 0xee, 0xb1,
	0xa3, 0x7d, 0x02, 0x2e, 0xb8, 0xa6, 0x8a, 0x17, 0xe0, 0xad, 0x78, 0x00, 0xaa, 0x78, 0x08, 0xaa,
	0x7f, 0x46, 0x1a, 0xc9, 0x72, 0x6a, 0x59, 0xa8, 0xe2, 0xce, 0xf3, 0x9d, 0xef, 0xfb, 0xd4, 0x7f,
	0xe7, 0xf4, 0x69, 0xc3, 0x0e, 0x53, 0x9a, 0x09, 0xc6, 0x95, 0xa6, 0x79, 0x8e, 0x32, 0xd6, 0xe3,
	0x02, 0x55, 0x58, 0x48, 0xa1, 0x05, 0x69, 0x5e, 0x1f, 0xd0, 0xbc, 0x18, 0xd2, 0x83, 0x9d, 0xde,
	0xd5, 0x4b, 0x15, 0x32, 0xb1, 0x4f, 0x0b, 0xb6, 0x9f, 0x08, 0x89, 0xfb, 0xd7, 0x07, 0xfb, 0x19,
	0x72, 0x94, 0x54, 0x63, 0xea, 0xd8, 0x3b, 0xcf, 0x6a, 0x9c, 0x42, 0xe4, 0x2c, 0x19, 0xef, 0x5f,
	0x1f, 0x5c, 0xa0, 0xa6, 0xef, 0xa7, 0xd2, 0x52, 0x0b, 0x95, 0xd0, 0x9c, 0xf1, 0x6c, 0x91, 0xeb,
	0x8b, 0x29, 0x75, 0x44, 0x93, 0x21, 0xe3, 0x28, 0xc7, 0xfb, 0xc5, 0x55, 0x66, 0x00, 0xb5, 0x3f,
	0x42, 0x4d, 0x17, 0xa9, 0xf6, 0xef, 0x52, 0xc9, 0x92, 0x6b, 0x36, 0xc2, 0x79, 0x41, 0xef, 0xef,
	0xcb, 0xb0, 0xda, 0xaf, 0x16, 0xe1, 0xac, 0xc0, 0x84, 0x3c, 0x87, 0x47, 0x7e, 0x55, 0xe2, 0x82,
	0x26, 0x57, 0x34, 0xc3, 0xb8, 0xa0, 0x7a, 0x18, 0x34, 0x76, 0x1b, 0x7b, 0x2b, 0x11, 0xf1, 0xb1,
	0x81, 0x0b, 0x0d, 0xa8, 0x1e, 0x92, 0x9f, 0xc2, 0x5a, 0x22, 0xb8, 0x96, 0xc2, 0x2e, 0x24, 0xa7,
	0x23, 0x0c, 0xee, 0x59, 0x72, 0x67, 0x0a, 0xbf, 0xa1, 0x23, 0x24, 0x5d, 0x58, 0x1a, 0x96, 0x17,
	0xc1, 0x92, 0x0d, 0x9a, 0x3f, 0x0d, 0xa2, 0x69, 0x16, 0xdc, 0x77, 0x88, 0xa6, 0x19, 0xf9, 0x18,
	0xd6, 0x53, 0xbc, 0xa4, 0x65, 0xae, 0xad, 0x93, 0x2a, 0x68, 0x82, 0xc1, 0x03, 0x1b, 0xef, 0xfa,
	0xc0, 0x9b, 0x0a, 0x27, 0x5f, 0xc3, 0xa6, 0xc4, 0x91, 0xd0, 0x18, 0x27, 0x79, 0xa9, 0x34, 0xca,
	0x38, 0x11, 0xfc, 0x92, 0x65, 0x01, 0xec, 0x36, 0xf6, 0x5a, 0x87, 0x3f, 0x0a, 0xab, 0x8d, 0x0c,
	0x23, 0x4b, 0x3b, 0x76, 0xac, 0x63, 0x4b, 0x8a, 0x36, 0xe4, 0x6d, 0x90, 0x0c, 0x80, 0x68, 0x49,
	0x2f, 0x2f, 0x59, 0x12, 0x8f, 0x28, 0xa7, 0x19, 0x8e, 0x90, 0xeb, 0xe0, 0x91, 0xf5, 0xfb, 0x70,
	0xea, 0x77, 0xee, 0x38, 0xaf, 0x27, 0x14, 0xef, 0xb9, 0xae, 0xe7, 0x03, 0x24, 0x84, 0x65, 0x77,
	0x2c, 0x82, 0x4d, 0xeb, 0xb2, 0x35, 0x75, 0x19, 0x58, 0xdc, 0x4b, 0x3d, 0x8b, 0xfc, 0x0a, 0x56,
	0x34, 0xe6, 0x38, 0x42, 0x2d, 0xc7, 0xc1, 0x96, 0x95, 0x6c, 0xd7, 0x7e, 0xb8, 0x0a, 0x79, 0xd5,
	0x94, 0x4b, 0x5e, 0x40, 0x53, 0x61, 0x52, 0x4a, 0xa6, 0xc7, 0xc1, 0x07, 0x56, 0x17, 0x4c, 0x75,
	0x67, 0x3e, 0xe2, 0x65, 0x13, 0x26, 0x79, 0x0d, 0xeb, 0x6e, 0xd1, 0xea, 0xf3, 0x0d, 0xac, 0x7c,
	0x77, 0x2a, 0x77, 0xb2, 0x5b, 0xd3, 0xed, 0x26, 0x73, 0x38, 0x79, 0x05, 0x6b, 0x8c, 0x67, 0x12,
	0x95, 0x8a, 0x33, 0xaa, 0xf1, 0x86, 0x8e, 0x83, 0xc7, 0xbb, 0x4b, 0x7b, 0xad, 0xc3, 0xc7, 0x53,
	0xb3, 0xbe, 0x23, 0xbc, 0x72, 0x71, 0x6f, 0xd5, 0x61, 0x33, 0x28, 0x39, 0x81, 0x0e, 0xce, 0xfa,
	0x3c, 0xb1, 0x3e, 0xb5, 0x4d, 0x3d, 0x5d, 0x60, 0xb3, 0x8a, 0x33, 0x2e, 0xaf, 0x80, 0xe0, 0x3b,
	0x8d, 0x92, 0xd3, 0x3c, 0x16, 0x85, 0x39, 0xfa, 0x42, 0xaa, 0xe0, 0xd0, 0x3a, 0xd5, 0x56, 0xe7,
	0xad, 0x0f, 0x55, 0xbb, 0x58, 0x69, 0x2a, 0x5c, 0xf5, 0x28, 0xac, 0x4d, 0xf3, 0x44, 0x53, 0x5d,
	0x2a, 0xf2, 0x63, 0x58, 0x2d, 0xa4, 0x78, 0x37, 0x8e, 0xfd, 0x31, 0xf7, 0x29, 0xd2, 0xb6, 0xe0,
	0xb1, 0xc3, 0xc8, 0x33, 0xe8, 0x2a, 0x96, 0x62, 0x42, 0x65, 0xcc, 0xf8, 0x37, 0x98, 0x68, 0x21,
	0x7d, 0x76, 0xac, 0x79, 0xbc, 0xef, 0xe1, 0xde, 0x5f, 0x1a, 0xb0, 0xb1, 0xe0, 0x9c, 0x92, 0x00,
	0x1e, 0x22, 0xa7, 0x17, 0x39, 0xa6, 0xf6, 0x17, 0x9a, 0x51, 0xf5, 0x49, 0x7e, 0x08, 0x2b, 0xd3,
	0x24, 0x71, 0xae, 0x53, 0x80, 0xfc, 0x16, 0xd6, 0x25, 0x2a, 0x51, 0xca, 0x04, 0x63, 0x71, 0x8d,
	0x52, 0xb2, 0x14, 0x83, 0x25, 0x3b, 0xf5, 0x6e, 0x6d, 0xea, 0x17, 0xe6, 0xe7, 0xa3, 0x6e, 0x45,
	0x7d, 0xeb, 0x99, 0xbd, 0x7f, 0x35, 0xe0, 0x83, 0x3b, 0x8e, 0xf9, 0xf7, 0x1e, 0xd2, 0x53, 0xe8,
	0x98, 0xba, 0xe7, 0x97, 0x82, 0x09, 0x6e, 0x8b, 0x41, 0x33, 0x5a, 0x35, 0x68, 0xbf, 0x02, 0xc9,
	0x4b, 0x68, 0x17, 0x2c, 0x17, 0xba, 0x4a, 0xe7, 0xfb, 0xf6, 0x38, 0x6e, 0xd6, 0x12, 0xc7, 0x44,
	0xfd, 0x66, 0xb5, 0x8a, 0xe9, 0x87, 0x55, 0x56, 0x7b, 0x62, 0x94, 0x0f, 0x6e, 0x29, 0xfd, 0xe6,
	0x38, 0xe5, 0xf4, 0xa3, 0xf7, 0xcf, 0x07, 0xd0, 0xaa, 0xd9, 0x92, 0x47, 0xf0, 0x20, 0xc5, 0x8b,
	0x32, 0xf3, 0x13, 0x74, 0x1f, 0x66, 0xe2, 0x7e, 0xdb, 0xec, 0xe4, 0x9a, 0x51, 0xf5, 0x69, 0xa6,
	0xa6, 0x25, 0x4d, 0x30, 0x56, 0x74, 0x54, 0x98, 0xaa, 0x6e, 0xa7, 0x76, 0x2f, 0x5a, 0xb5, 0xe8,
	0x99, 0x07, 0xc9, 0x17, 0xb0, 0x52, 0xad, 0xb4, 0x39, 0x87, 0x66, 0x74, 0x7b, 0xa1, 0xab, 0xda,
	0x21, 0x2d, 0x58, 0x68, 0x6e, 0x99, 0xf0, 0xda, 0x14, 0x2c, 0x47, 0x8a, 0xf0, 0x4f, 0x25, 0x93,
	0x76, 0xed, 0x55, 0x34, 0x95, 0x92, 0xaf, 0xa1, 0x39, 0x2c, 0x68, 0xac, 0x0a, 0x4c, 0x82, 0x4f,
	0xac, 0xcd, 0xa7, 0x75, 0x9b, 0xda, 0xed, 0x62, 0xdc, 0x7e, 0x27, 0x24, 0xfb, 0x56, 0x70, 0x4d,
	0xf3, 0x81, 0x48, 0x8f, 0x7c, 0xcc, 0x15, 0xfc, 0xe8, 0xe1, 0xb0, 0xa0, 0xb6, 0xf2, 0x5f, 0xc0,
	0x66, 0x21, 0xd2, 0x38, 0x65, 0x4a, 0x96, 0x85, 0xd9, 0x87, 0xf8, 0xa2, 0x4c, 0x33, 0xd4, 0xc1,
	0x0b, 0xeb, 0x1f, 0xd6, 0xfd, 0x5d, 0xad, 0x0a, 0xfd, 0x45, 0x17, 0x0e, 0x44, 0x7a, 0x32, 0x91,
	0x7d, 0x6e, 0x55, 0xd1, 0x46, 0x71, 0x1b, 0x24, 0x27, 0xd0, 0xe6, 0x22, 0xc5, 0x33, 0xcc, 0x5d,
	0x2a, 0xfc, 0xd2, 0x17, 0x9a, 0x05, 0x2b, 0xf0, 0xa6, 0xc6, 0x8b, 0x66, 0x54, 0x24, 0x82, 0x35,
	0x9a, 0xa6, 0xcc, 0xf8, 0xd2, 0x3c, 0xa6, 0x32, 0x53, 0xc1, 0x6f, 0xec, 0xb9, 0x7e, 0xb6, 0xf0,
	0x88, 0x84, 0x47, 0x13, 0xf2, 0x91, 0xcc, 0xd4, 0x29, 0xd7, 0x72, 0x1c, 0x75, 0xe8, 0x0c, 0x48,
	0x9e, 0xc3, 0x12, 0xf2, 0xeb, 0xe0, 0x8b, 0xf9, 0x62, 0x55, 0xf7, 0x39, 0xe5, 0xd7, 0x4e, 0x6c,
	0xa8, 0x8b, 0xf3, 0x2b, 0xfd, 0xae, 0xf9, 0xb5, 0x73, 0x04, 0x1b, 0x0b, 0xc6, 0x65, 0xae, 0xc4,
	0x2b, 0x1c, 0xfb, 0x5a, 0x62, 0xfe, 0x34, 0x27, 0xf1, 0x9a, 0xe6, 0x65, 0x95, 0x4e, 0xee, 0xe3,
	0xb3, 0x7b, 0x2f, 0x1b, 0x3b, 0x9f, 0x42, 0xb3, 0x1a, 0xd2, 0x7f, 0xa2, 0xeb, 0xfd, 0xa3, 0x0d,
	0xad, 0x5a, 0x22, 0xdc, 0x71, 0xd6, 0x1f, 0x03, 0x14, 0x92, 0x5d, 0xb3, 0x1c, 0x33, 0x4c, 0xfd,
	0x71, 0xaf, 0x21, 0xe6, 0xde, 0x77, 0x59, 0x1f, 0x9b, 0x2d, 0x4b, 0xcb, 0x51, 0xe1, 0xb3, 0xb9,
	0xe3, 0xe0, 0x63, 0x8f, 0x92, 0x33, 0x58, 0x67, 0x5c, 0xa3, 0x4c, 0xd0, 0x1d, 0xab, 0x91, 0x48,
	0xd1, 0xe6, 0x74, 0xe7, 0xf0, 0x27, 0x0b, 0x33, 0x33, 0xec, 0xd7, 0xe8, 0xaf, 0x45, 0x8a, 0x51,
	0x97, 0xcd, 0x21, 0xe4, 0x09, 0xb4, 0x94, 0xad, 0xc3, 0x71, 0x21, 0xa4, 0xb6, 0x89, 0xbe, 0x1a,
	0x81, 0x83, 0x06, 0x42, 0x6a, 0xf2, 0x33, 0x58, 0x67, 0x23, 0xdb, 0xbe, 0x94, 0xa6, 0x97, 0x71,
	0x57, 0xf0, 0xb2, 0x2b, 0xbd, 0x36, 0x30, 0x28, 0xf3, 0xdc, 0xdd, 0xc0, 0x64, 0x0f, 0xba, 0xae,
	0x6c, 0x30, 0xce, 0x74, 0x6c, 0xa3, 0xc1, 0x43, 0xd7, 0xc3, 0x58, 0xbc, 0xcf, 0x99, 0xee, 0x1b,
	0xd4, 0xba, 0xf2, 0x24, 0x2f, 0x53, 0x8c, 0x59, 0x11, 0x4b, 0xca, 0x33, 0x54, 0x41, 0xd3, 0xbb,
	0xba, 0x40, 0xbf, 0x88, 0x2c, 0x6c, 0xb8, 0xf8, 0x6e, 0x9e, 0xbb, 0xe2, 0xb8, 0x3e, 0x30, 0xe1,
	0x1e, 0xc2, 0xe6, 0xc4, 0x97, 0x5f, 0x88, 0x92, 0xa7, 0x76, 0x5e, 0xca, 0xb6, 0x32, 0x2b, 0xd1,
	0x46, 0xe5, 0xed, 0x62, 0x66, 0x82, 0x56, 0x33, 0xf1, 0x9f, 0xd1, 0xb4, 0x9c, 0xa6, 0xfa, 0x8d,
	0xba, 0xc6, 0x35, 0x6b, 0x1c, 0x13, 0x1d, 0x9b, 0x86, 0x50, 0x94, 0x3a, 0x68, 0x4f, 0x9a, 0x35,
	0x03, 0x9f, 0x3b, 0xd4, 0xd4, 0xb3, 0x54, 0x52, 0xc6, 0xe3, 0xb4, 0x94, 0xd4, 0x96, 0xea, 0x55,
	0xcb, 0x5b, 0xb5, 0xe8, 0x89, 0x07, 0xc9, 0x4b, 0x08, 0x0a, 0x2a, 0x91, 0xeb, 0x58, 0x0d, 0x4b,
	0x9d, 0x8a, 0x9b, 0x9a, 0xa0, 0x63, 0x05, 0x5b, 0x2e, 0x7e, 0xe6, 0xc3, 0x13, 0xe5, 0x2e, 0xb4,
	0x12, 0xc1, 0x93, 0x52, 0x4a, 0xe4, 0xc9, 0x38, 0x58, 0xb3, 0x1b, 0x58, 0x87, 0xcc, 0x10, 0xaa,
	0xbe, 0x2e, 0x15, 0x23, 0xca, 0x78, 0xd0, 0x75, 0x43, 0xf0, 0xe8, 0x89, 0x05, 0xc9, 0xaf, 0x61,
	0xdb, 0xd6, 0x2d, 0xae, 0x62, 0x85, 0x54, 0x26, 0xc3, 0x69, 0xe7, 0xa8, 0x82, 0x75, 0x3f, 0x06,
	0x91, 0x9e, 0x70, 0x75, 0x66, 0xc3, 0x93, 0xfe, 0x51, 0x91, 0x63, 0x58, 0xc9, 0x59, 0x36, 0xd4,
	0x4a, 0x63, 0x11, 0x3c, 0xb6, 0xb5, 0xe8, 0xe9, 0xe2, 0x13, 0xf9, 0x55, 0x45, 0xab, 0xfa, 0xae,
	0x89, 0x8e, 0x7c, 0x06, 0xcb, 0xdf, 0xb2, 0xe2, 0x8a, 0xf1, 0xe0, 0x89, 0x75, 0xe8, 0x2d, 0x76,
	0xf8, 0xa3, 0xe5, 0x54, 0xcd, 0x9e, 0x53, 0x90, 0xa7, 0xb0, 0xa4, 0x52, 0x15, 0xec, 0x59, 0xe1,
	0x46, 0xad, 0x5d, 0x4b, 0x95, 0x67, 0x9a, 0x38, 0xf9, 0x1c, 0xd6, 0x24, 0xd2, 0x94, 0x71, 0xd3,
	0x0f, 0x15, 0x52, 0x5c, 0xa0, 0xbf, 0x3b, 0xb6, 0x17, 0x55, 0xce, 0x81, 0x21, 0x44, 0x9d, 0x89,
	0xc2, 0x7e, 0xcf, 0xde, 0x3c, 0x9f, 0x7c, 0xff, 0x9b, 0xe7, 0x3b, 0x15, 0xdf, 0xda, 0xbc, 0xff,
	0xab, 0xe2, 0x5b, 0xf3, 0xf9, 0x9f, 0x16, 0xdf, 0x3f, 0x37, 0x60, 0x6d, 0x6e, 0x4b, 0xcd, 0xdd,
	0x4e, 0xd3, 0xd4, 0x74, 0x8f, 0xbe, 0x8a, 0x56, 0x9f, 0xe4, 0x43, 0x68, 0xd3, 0x24, 0x31, 0x6b,
	0xaf, 0xc5, 0x15, 0x72, 0x5f, 0x50, 0x5b, 0x0e, 0x3b, 0x37, 0x10, 0xd9, 0x85, 0x76, 0x42, 0xe3,
	0x04, 0xa5, 0x76, 0xcf, 0x25, 0xf7, 0xc8, 0x81, 0x84, 0x1e, 0xa3, 0xd4, 0xf6, 0x99, 0xb4, 0x05,
	0xcb, 0xb6, 0xe9, 0x76, 0xa5, 0xaf, 0x19, 0xf9, 0xaf, 0x9d, 0x3d, 0x68, 0xd7, 0x8f, 0xc6, 0xdd,
	0xc3, 0xf8, 0x7f, 0xde, 0x18, 0x3f, 0x87, 0xee, 0x7c, 0x4d, 0x26, 0x6d, 0x68, 0x46, 0xa7, 0x27,
	0xfd, 0xe8, 0xf4, 0xf8, 0xbc, 0xfb, 0x03, 0x02, 0xb0, 0x7c, 0x3e, 0x88, 0xde, 0xfe, 0xfe, 0x0f,
	0xdd, 0x46, 0xaf, 0x03, 0xed, 0xfa, 0xd3, 0xa6, 0xb7, 0x0e, 0x6b, 0x73, 0xef, 0x96, 0x5e, 0x17,
	0x3a, 0xb3, 0x4f, 0x92, 0x5e, 0x00, 0x5b, 0x8b, 0x5f, 0x19, 0xbd, 0x2d, 0x78, 0xb4, 0xe8, 0xc9,
	0xd0, 0xdb, 0x84, 0x8d, 0x05, 0x4f, 0x80, 0xde, 0x18, 0x3a, 0xb3, 0xfd, 0xbc, 0xe9, 0xd4, 0x47,
	0x94, 0xb3, 0x4b, 0x54, 0xba, 0xfe, 0x98, 0x6d, 0x57, 0xa0, 0xdd, 0x9f, 0xf7, 0x77, 0xae, 0x1f,
	0xc1, 0x7d, 0xdb, 0x6b, 0x2d, 0xd9, 0xc4, 0xb9, 0x7d, 0xc4, 0x6c, 0xb4, 0x57, 0x40, 0xa7, 0xaf,
	0x34, 0x13, 0x93, 0xa7, 0x02, 0xf9, 0x78, 0x46, 0xf7, 0x41, 0xfd, 0x11, 0x54, 0x7b, 0x75, 0x3b,
	0x39, 0x39, 0x80, 0x65, 0x77, 0x81, 0xf9, 0x8e, 0x77, 0x7b, 0x11, 0xdd, 0x12, 0x22, 0x4f, 0xec,
	0xfd, 0xad, 0x01, 0xcb, 0x6e, 0x08, 0xe4, 0x2b, 0x68, 0x8e, 0x50, 0xd3, 0x94, 0x6a, 0x6a, 0x27,
	0xd8, 0x3a, 0x7c, 0x5e, 0xcb, 0xef, 0xc9, 0xff, 0x03, 0xc2, 0xe2, 0x2a, 0x33, 0x80, 0x0a, 0x0d,
	0xdb, 0x64, 0xbc, 0xd3, 0xbf, 0x46, 0x4d, 0xa3, 0x89, 0x03, 0x39, 0x82, 0xfb, 0xd6, 0xe9, 0x9e,
	0x75, 0xfa, 0xc5, 0x9d, 0x4e, 0xfe, 0x3f, 0x0b, 0x61, 0x44, 0x6f, 0x4e, 0xdf, 0x69, 0xe4, 0x8a,
	0x09, 0x1e, 0x59, 0x69, 0xef, 0xaf, 0x0d, 0x58, 0x99, 0x14, 0xb2, 0xf7, 0xbc, 0x19, 0xb6, 0xa1,
	0x59, 0xa6, 0xca, 0xed, 0x8c, 0x5b, 0xf8, 0x87, 0x65, 0xaa, 0xec, 0xa6, 0x84, 0xb0, 0x51, 0x2a,
	0x8c, 0xb5, 0x2c, 0x95, 0xbe, 0x11, 0x52, 0x0f, 0xc7, 0xf1, 0x37, 0x37, 0xda, 0xf7, 0x19, 0xeb,
	0xa5, 0xc2, 0xf3, 0x69, 0xe4, 0xcb, 0x1b, 0x4d, 0x3e, 0x82, 0x8e, 0xe1, 0x73, 0x21, 0x47, 0x34,
	0xb7, 0x54, 0x97, 0x6c, 0xed, 0x52, 0xe1, 0x1b, 0x0b, 0x7e, 0x79, 0xa3, 0xff, 0x1d, 0x00, 0x00,
	0xff, 0xff, 0x3d, 0xe3, 0xde, 0xbe, 0xfd, 0x11, 0x00, 0x00,
}
