hub: docker.io/istio
tag: 1.1.4
trafficManagement:
  enabled: true
  components:
    namespace: istio-control
    proxy:
      common:
        values:
          image: proxyv2
          clusterDomain: "cluster.local"
          # Resources for the sidecar.
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 2000m
              memory: 128Mi
          concurrency: 2
          accessLogEncoding: TEXT
          logLevel: warning
          componentLogLevel: "misc:error"
          dnsRefreshRate: 300s
          privileged: false
          enableCoreDump: false
          statusPort: 15020
          readinessInitialDelaySeconds: 1
          readinessPeriodSeconds: 2
          readinessFailureThreshold: 30
          includeIPRanges: "*"
          autoInject: enabled
          tracer: "zipkin"

policy:
  enabled: true
  components:
    namespace: istio-policy

telemetry:
  enabled: true
  components:
    namespace: istio-telemetry

security:
  enabled: true
  components:
    namespace: istio-security

configManagement:
  enabled: true
  components:
    namespace: istio-control

autoInjection:
  enabled: true
  components:
    namespace: istio-control

values:
  logging:
    level: "default:info"
  k8sIngress:
    enabled: false
    gatewayName: ingressgateway
    enableHttps: false
  proxy_init:
    image: proxy_init
  imagePullPolicy: Always
  controlPlaneSecurityEnabled: true
  disablePolicyChecks: true
  policyCheckFailOpen: false
  enableTracing: true
  mtls:
    enabled: false
  arch:
    amd64: 2
    s390x: 2
    ppc64le: 2
  oneNamespace: false
  configValidation: true
  defaultResources:
    requests:
      cpu: 10m
  defaultPodDisruptionBudget:
    enabled: true
  useMCP: true
  outboundTrafficPolicy:
    mode: ALLOW_ANY
